#buildspec.yml

version: 0.2

phases:
  build:
    commands:
#        - docker build -d Dockerfile -t 974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:${!CODEBUILD_BUILD_ID#*:}' .
       - $(aws ecr get-login --region us-east-1)
       - 'docker ps' 
       - 'time=$(date +"%d%m%Y-%H%M%S")'
#       - var=$(aws ecr list-images --repository-name nonprod | head -5  | awk 'NR==4 {print $2}' | sed 's/\"//g' | sed 's/\,//g')
       - var=$(aws ecr list-images --repository-name nonprod | grep -i tomcat | awk 'NR==1 {print $2}' | sed 's/\"//g' | sed 's/\,//g')
       - echo $var
       - sed -i "s/974293703167.dkr.ecr.us-east-1.amazonaws.com\/nonprod:tomcat/974293703167.dkr.ecr.us-east-1.amazonaws.com\/nonprod:${var}/g" Dockerfile
       - 'docker build -f Dockerfile -t 974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:${time} .'
#       - 'docker build -f Dockerfile -t 974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:tomcat .'
  post_build:
    commands:
#       - 'eval $(aws ecr get-login) && docker push 974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:${!CODEBUILD_BUILD_ID#*:}'
       - 'docker push 974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:${time}'
#       - 'echo "974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:${time}" > image.txt'
       - 'echo "{ \"image\": \"974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:${time}\"}" > image.json'
#       - 'docker push 974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:tomcat' 
#       - 'echo "{ \"image\": \"974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:tomcat\"}" > image.json'
#       - 'echo "974293703167.dkr.ecr.us-east-1.amazonaws.com/nonprod:tomcat" > image.txt'

artifacts:
  files:
    - image.json
#    - image.txt
    - ecs.json
    - config.json
  discard-paths: yes

