db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "name":"Acceptance", "description":"Explore topics that discuss the importance of having tolerance for people who work, think and act differently than you.", "personalityType" : [ "Refiner", "Researcher"] });
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "name":"Accountability", "description":"Learn how success is tied to responsibility and how to take ownership by addressing issues and admitting failures.", "personalityType" : [] });
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "name":"Active Listening","description":"Master the art of active listening through a conscious effort to understand what people are saying and what they actually mean.", "personalityType" : [ "Encourager", "Innovator", "Instructor","Motivator","Promoter" ] });
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "name":"Appreciation","description":"Grasp a full understanding of situations to better show recognition and enjoyment to the work of others.", "personalityType" : [ "Examiner", "Navigator", "Pragmatist","Researcher","Visionary" ] });
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "name":"Assertiveness","description":"Find ways of being self-assured and confident without being aggressive.", "personalityType" : [ "Ambassador"] });
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "name":"Attention to Detail","description":"Develop habits to handle complex tasks in fast-paced scenarios while still adhering to big picture thinking.", "personalityType" : [ "Ambassador", "Encourager", "Innovator","Instructor","Motivator", "Promoter","Supporter"] });
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "name":"Awareness of Others","description":"Cultivate an appreciation for the different approaches and work styles of others.", "personalityType" : [ "Designer", "Examiner", "Refiner","Supporter" ] });
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : ["Actuary","Tough_N_Tender"],"name":"Big Picture Thinking","description":"Gain the capacity to look beyond the details to see the bigger picture and become a global thinker."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Building Stability","description":"Develop the aptitude necessary to acquire assets, position, education and a sense of belonging by finding motivation through stability."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : ["Visionary"],"name":"Communicating for Results","description":"Identify ways to become a well-rounded communicator through proven and interpersonal communication approaches."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Actuary", "Innovator", "Instructor","Visionary" ],"name":"Compassion","description":"Establish a standard sense of regard for the emotions and feelings of others."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Navigator", "Actuary", "Refiner","Visionary" ],"name":"Compromise","description":"Become a strong-willed negotiator with the depth to concede and the breadth to suggest mutually beneficial arrangements."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : ["Actuary","Ambassador","Designer","Encourager","Examiner","Navigator","Pragmatist","Promoter","Refiner","Supporter","Tough_N_Tender"],"name":"Constructive Criticism","description":"Learn more about giving and receiving a well-meant critique that’s intended to help and improve."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Collaboration","description":"Discover ways to create a collaborative environment where individuals feel comfortable expressing their ideas and being themselves."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Critical Thinking","description":"Seek the skills that elevate the thought process to help make clear and well-reasoned decisions"});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Actuary", "Designer", "Encourager","Navigator","Pragmatist" ],"name":"Decision Making","description":"Cultivate a capacity to extract good decisions from bad ones and energize the ability to quickly make better decisions."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Ambassador", "Encourager", "Promoter","Refiner","Visionary" ],"name":"Delegation","description":"Mitigate tasks and take accountability by instructing others on how to reach objectives and goals."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Effective Management","description":"Consider techniques for organizing people around a central ambition and learn to guide them towards a mutual objective."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Motivator", "Refiner", "Researcher","Supporter","Tough_N_Tender" ],"name":"Embracing Change","description":"Keep calm and tackle changes head on by letting go of routines and accepting new incidents as possibilities."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Encouraging Imagination","description":"Become a dreamer and embolden others to do the same in order to gain insight into new possibilities."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Engaging Conversation","description":"Sharpen communication by developing a skill set around open-ended questions and initiating deeper conversations."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Navigator", "Refiner", "Researcher" ,"Supporter","Tough_N_Tender"],"name":"Flexibility","description":"Accept the necessary changes to become extensible with work, tasks and relationships."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Pragmatist", "Promoter"],"name":"Focus","description":"Maintain a locus of control to concentrate on tasks, campaigns and objectives."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : ["Actuary","Ambassador","Encourager","Innovator","Instructor","Motivator","Promoter","Visionary"],"name":"Forethought & Planning","description":"Learn the power of thinking before acting and how to utilize finer details to plot a path to victory."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Examiner"],"name":"Getting to the Point","description":"Examine the need for cutting out details to get across main points that paint the big picture."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ ],"name":"Social Awareness","description":"Develop the dexterity to recognize the talents and strengths of others, while paying attention to the group’s relational health."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Hedging Statements","description":"Investigate the art of providing information by dismissing definitive statements and opting for prefacing statements."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Incorporating Creativity","description":"Cultivate an appreciation for the creative process and encourage left-brain thinkers to encompass right-brain thinking."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Intuitive Thinking","description":"Let your instincts thrive with unconscious reasoning by letting go of logic and embracing a natural propensity to understanding."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Ambassador", "Promoter" ],"name":"Logic & Rationale","description":"Determine the best course of action by establishing rules for factual thinking and how to set them in motion."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Actuary", "Ambassador", "Encourager","Examiner","Motivator","Pragmatist","Researcher","Supporter","Tough_N_Tender","Visionary" ],"name":"Managing Differences","description":"Address conflict before it happens by celebrating individuality and building better relationships."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Visionary"],"name":"Patience","description":"Stay calm under pressure by learning to accept situations and others when dealing with delay."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Researcher"],"name":"Persuasion","description":"Gain a competitive advantage by enticing others to consider their position based on information, feelings and reason."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [],"name":"Presentation Skills","description":"Improve public speaking and information delivery through tried and true techniques, that increase attention and retention."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Promoter"],"name":"Presenting Facts","description":"Demonstrate supporting evidence with examples, facts and details to illustrate the decision making process."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Tough_N_Tender" ],"name":"Receptivity to New Ideas","description":"Become receptive to contrasting beliefs by understanding different forms of thinking."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Innovator", "Instructor","Navigator","Pragmatist","Refiner","Researcher","Tough_N_Tender" ],"name":"Relationship Building","description":"Accomplish stronger communication by building an authentic accord and trust with others."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Refiner", "Tough_N_Tender", "Visionary" ],"name":"Releasing Control","description":"Learn to trust others and go with the group by handing over command and authority."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Designer", "Navigator", "Refiner","Researcher" ],"name":"Satisfaction","description":"Overcome the need for perfection, find a personal balance and learn to seek gratification from everyday situations and scenarios."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Actuary", "Ambassador", "Designer","Encourager","Examiner","Innovator","Instructor","Motivator","Navigator","Pragmatist","Promoter","Refiner","Supporter","Tough_N_Tender"],"name":"Seeking Feedback","description":"Discern how and when, to actively approach others when information is limited, instructions are unclear, purpose is unknown or advice is needed."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Supporter" ],"name":"Self Awareness","description":"Gain a greater sense of self and the affect that actions, behaviors and personal ethics have on individual surroundings."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Actuary", "Examiner", "Motivator","Refiner" ],"name":"Separating Out Emotions","description":"Determine ways to stay calm during emotional situations and how to remain objective at all costs."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Encourager", "Examiner", "Motivator","Promoter","Visionary" ],"name":"Setting Expectations","description":"Explore step by step processes for gaining results by expressing key needs and intentions."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ ],"name":"Showing Consideration","description":"Master etiquette in the workplace by interpreting how and when to adjust to the needs of others."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Visionary"],"name":"Showing Empathy","description":"Acknowledge others through the use of compassion and kindness to be supportive of their efforts and situations."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Ambassador", "Supporter" ],"name":"Speaking Up","description":"Consider the outcome of failing to share opinions, provide facts or to the overall conversation; especiSupporter when doing so would create opportunity."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Supporter"],"name":"Speaking with Purpose","description":"Become more declarative and confident when speaking."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Actuary", "Designer", "Pragmatist","Refiner" ],"name":"Taking Action","description":"Develop a capacity to move from theory to application and knowing how and when to begin."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Designer", "Navigator", "Pragmatist","Refiner","Supporter" ],"name":"Taking Risks","description":"Establish an understanding of how taking risks can benefit everyone and lead to better outcomes."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Ambassador", "Encourager", "Examiner","Innovator","Instructor","Motivator","Promoter","Visionary" ],"name":"Task Completion","description":"Learn to manage workload and break down priorities, in order to meet objectives and expectations."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Visionary" ],"name":"Team Building","description":"Facilitate better teams by understanding how to employ talent based on skills matching."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Designer", "Innovator", "Instructor","Navigator","Visionary" ],"name":"Teamwork","description":"Learn how to integrate into a team and provide value, by building dynamic relationships and collaborating effectively."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Actuary", "Ambassador", "Encourager","Innovator","Instructor","Motivator","Pragmatist","Promoter" ],"name":"Time Management","description":"Achieve goals and meet deadlines with tips and tricks to manage workloads and prioritize tasks."});
db.sPGoal.insert({"_class" : "com.sp.web.model.SPGoal","category":"GrowthAreas", "personalityType" : [ "Examiner", "Researcher", "Tough_N_Tender" ],"name":"Work Life Balance","description":"Take an active stance on personal time, achievement and success by balancing work and home, activity and rest."});
db.sPGoal.update({name:"Acceptance"}, {$set:{description:"Explore ways to work with and support people who think, act and work differently than you."}})
db.sPGoal.update({name:"Accountability"}, {$set:{description:"Be aware of how personal responsibility contributes to your success. Learn how to take ownership by addressing problems and admitting shortcomings."}})
db.sPGoal.update({name:"Active Listening"}, {$set:{description:"Master the art of listening and asking questions to elicit more information, understand people more deeply and grasp the unspoken."}})
db.sPGoal.update({name:"Appreciation"}, {$set:{description:"Grasp a full understanding of people to better show recognition of and gratitude for the work of others."}})
db.sPGoal.update({name:"Attention to Detail"}, {$set:{description:"Develop habits to achieve thoroughness and accuracy without losing sight of the big picture."}})
db.sPGoal.update({name:"Awareness of Others"}, {$set:{description:"Cultivate interpersonal awareness and develop greater sensitivity to others’ needs and interests."}})
db.sPGoal.update({name:"Big Picture Thinking"}, {$set:{description:"Gain the capacity to look beyond the details to see the bigger picture and become a global thinker."}})
db.sPGoal.update({name:"Building Stability"}, {$set:{description:"Cultivate practices that create a consistent, predictable environment to enable your own and others’ productivity."}})
db.sPGoal.update({name:"Communicating for Results"}, {$set:{description:"Identify ways to become a high-impact communicator through proven interpersonal communication approaches."}})
db.sPGoal.update({name:"Compassion"}, {$set:{description:"Establish a sense of regard for the emotions and feelings of others."}})
db.sPGoal.update({name:"Compromise"}, {$set:{description:"Develop the ability to build consensus through a willingness to concede points, make tradeoffs and secure support through mutually beneficial solutions."}})
db.sPGoal.update({name:"Constructive Criticism"}, {$set:{description:"Learn more about giving and receiving feedback to help improve performance."}})
db.sPGoal.update({name:"Collaboration"}, {$set:{description:"Discover ways to create an environment where individuals feel comfortable expressing their ideas through an open and meaningful exchange of perspectives."}})
db.sPGoal.update({name:"Critical Thinking"}, {$set:{description:"Seek the capability to analyze issues in depth, understand implications and weigh tradeoffs of alternative strategies."}})
db.sPGoal.update({name:"Decision Making"}, {$set:{description:"Build a capacity to discern good decisions from bad ones and strengthen the ability to make better, faster decisions."}})
db.sPGoal.update({name:"Delegation"}, {$set:{description:"Entrust tasks to others and provide instruction to help them reach objectives and goals."}})
db.sPGoal.update({name:"Effective Management"}, {$set:{description:"Develop techniques to organize people around a goal and guide them towards a shared objective."}})
db.sPGoal.update({name:"Embracing Change"}, {$set:{description:"Tackle changes head-on by letting go of routine and accepting new circumstances as possibilities."}})
db.sPGoal.update({name:"Encouraging Imagination"}, {$set:{description:"Embolden yourself and others to think big and explore new possibilities."}})
db.sPGoal.update({name:"Engaging Conversation"}, {$set:{description:"Sharpen your skills at initiating conversation, getting people to open up to you and connecting more deeply."}})
db.sPGoal.update({name:"Flexibility"}, {$set:{description:"Build your personal adaptability and become more flexible in your work and relationships."}})
db.sPGoal.update({name:"Focus"}, {$set:{description:"Maintain a locus of control to concentrate on tasks, campaigns and objectives."}})
db.sPGoal.update({name:"Forethought & Planning"}, {$set:{description:"Learn to think before acting, develop a more robust thought process and use a methodical approach to organizing and executing work. ."}})
db.sPGoal.update({name:"Getting to the Point"}, {$set:{description:"Enhance the ability to use concise communications that convey your thinking in a succinct, powerful manner."}})
db.sPGoal.update({name:"Social Awareness"}, {$set:{description:"Develop the ability to recognize and foster the strengths of people and teams. Understand a group’s relational and team health and learn to foster it."}})
db.sPGoal.update({name:"Hedging Statements"}, {$set:{description:"Investigate the art of providing information by dismissing definitive statements and opting for prefacing statements."}})
db.sPGoal.update({name:"Incorporating Creativity"}, {$set:{description:"Develop yourself as an imaginative thinker capable of generating novel ideas and strategies."}})
db.sPGoal.update({name:"Intuitive Thinking"}, {$set:{description:"Rely on your instincts, unconscious reasoning and gut feel to make rapid judgments."}})
db.sPGoal.update({name:"Logic & Rationale"}, {$set:{description:"Use facts, information and analysis to determine an effective course of action."}})
db.sPGoal.update({name:"Managing Differences"}, {$set:{description:"Address conflict before it happens by celebrating individuality and building better relationships."}})
db.sPGoal.update({name:"Patience"}, {$set:{description:"Learn to work at different paces, deal with delays and stay calm under pressure."}})
db.sPGoal.update({name:"Persuasion"}, {$set:{description:"Gain skill at influencing others to support your requests and ideas."}})
db.sPGoal.update({name:"Presentation Skills"}, {$set:{description:"Improve public speaking and information delivery through tried and true techniques of effective presenters."}})
db.sPGoal.update({name:"Presenting Facts"}, {$set:{description:"Support your ideas with examples, facts and details to convey a persuasive case for your thinking."}})
db.sPGoal.update({name:"Receptivity to New Ideas"}, {$set:{description:"Become receptive to contrasting beliefs by understanding different forms of thinking."}})
db.sPGoal.update({name:"Relationship Building"}, {$set:{description:"Enhance your relational intelligence and learn to build trust and an authentic accord with others."}})
db.sPGoal.update({name:"Releasing Control"}, {$set:{description:"Learn to trust others and go with the group by ceding authority and empowering others."}})
db.sPGoal.update({name:"Satisfaction"}, {$set:{description:"Overcome the need for perfection, find personal balance and learn to seek gratification from everyday situations and scenarios."}})
db.sPGoal.update({name:"Seeking Feedback"}, {$set:{description:"Discern how and when to solicit feedback that will help improve performance and hone efforts."}})
db.sPGoal.update({name:"Self Awareness"}, {$set:{description:"Gain a greater sense of self and the effect that actions, behaviors and personal ethics have on others."}})
db.sPGoal.update({name:"Separating Out Emotions"}, {$set:{description:"Determine ways to manage emotions during trying circumstances and maintain objectivity."}})
db.sPGoal.update({name:"Setting Expectations"}, {$set:{description:"Explore step-by-step processes for gaining results by expressing key needs and intentions."}})
db.sPGoal.update({name:"Showing Consideration"}, {$set:{description:"Interpret how and when to adjust to the needs of others through a more attentive, helpful interpersonal style."}})
db.sPGoal.update({name:"Showing Empathy"}, {$set:{description:"Demonstrate compassion and kindness through supporting people and acknowledge their efforts and circumstances."}})
db.sPGoal.update({name:"Speaking Up"}, {$set:{description:"Learn how to share your thoughts and ideas, including in challenging situations."}})
db.sPGoal.update({name:"Speaking with Purpose"}, {$set:{description:"Become more declarative and confident when speaking."}})
db.sPGoal.update({name:"Taking Action"}, {$set:{description:"Develop a capacity to move from theory to application and drive progress on work efforts."}})
db.sPGoal.update({name:"Taking Risks"}, {$set:{description:"Establish comfort with taking risk to achieve better outcomes and maximize results."}})
db.sPGoal.update({name:"Task Completion"}, {$set:{description:"Organize, prioritize and segment work to meet objectives and expectations."}})
db.sPGoal.update({name:"Team Building"}, {$set:{description:"Facilitate better teams by understanding how to employ talent based on skills matching."}})
db.sPGoal.update({name:"Teamwork"}, {$set:{description:"Learn how to integrate into a team and work effectively in a group setting."}})
db.sPGoal.update({name:"Time Management"}, {$set:{description:"Achieve goals and meet deadlines with strategies and techniques to maximize productivity and manage workloads."}})
db.sPGoal.update({name:"Work Life Balance"}, {$set:{description:"Take an active stance on personal time, achievement and success by balancing work and home, activity and rest."}})
db.sPGoal.update({name:"Setting Expectations"}, {$set:{"personalityType" : ["Encourager","Examiner","Motivator","Promoter","Visionary"]}});
db.sPGoal.update({name:"Getting to the Point"}, {$set:{"personalityType" : ["Examiner"]}});
db.sPGoal.update({name:"Work Life Balance"}, {$set:{"personalityType" : ["Examiner","Researcher","Tough_N_Tender"]}});
db.sPGoal.update({name:"Showing Empathy"}, {$set:{"personalityType" : ["Visionary"]}});
db.sPGoal.update({name:"Task Completion"}, {$set:{"personalityType" : ["Ambassador","Encourager","Examiner","Innovator","Instructor","Motivator","Promoter","Visionary"]}});
db.sPGoal.update({name:"Showing Consideration"}, {$set:{"personalityType" : ["Designer","Motivator","Navigator"]}});
db.sPGoal.update({name:"Constructive Criticism"}, {$set:{"personalityType" : ["Actuary","Ambassador","Designer","Encourager","Examiner","Navigator","Pragmatist","Promoter","Refiner","Supporter","Tough_N_Tender"]}});
db.sPGoal.update({name:"Teamwork"}, {$set:{"personalityType" : ["Designer","Innovator","Instructor","Navigator","Visionary"]}});
db.sPGoal.update({name:"Compassion"}, {$set:{"personalityType" : ["Actuary","Innovator","Instructor","Visionary"]}});
db.sPGoal.update({name:"Compromise"}, {$set:{"personalityType" : ["Actuary","Designer","Navigator","Refiner","Visionary"]}});
db.sPGoal.update({name:"Building Stability"}, {$set:{"personalityType" : ["Innovator","Motivator","Tough_N_Tender"]}});
db.sPGoal.update({name:"Relationship Building"}, {$set:{"personalityType" : ["Innovator","Instructor","Navigator","Pragmatist","Refiner","Researcher","Tough_N_Tender"]}});
db.sPGoal.update({name:"Embracing Change"}, {$set:{"personalityType" : ["Motivator","Refiner","Researcher","Supporter","Tough_N_Tender"]}});
db.sPGoal.update({name:"Big Picture Thinking"}, {$set:{"personalityType" : ["Actuary","Tough_N_Tender"]}});
db.sPGoal.update({name:"Delegation"}, {$set:{"personalityType" : ["Ambassador","Encourager","Promoter","Refiner","Visionary"]}});
db.sPGoal.update({name:"Acceptance"}, {$set:{"personalityType" : ["Refiner","Researcher","Researcher"]}});
db.sPGoal.update({name:"Time Management"}, {$set:{"personalityType" : ["Actuary","Ambassador","Encourager","Innovator","Instructor","Motivator","Pragmatist","Promoter"]}});
db.sPGoal.update({name:"Decision Making"}, {$set:{"personalityType" : ["Actuary","Designer","Encourager","Navigator","Pragmatist"]}});
db.sPGoal.update({name:"Flexibility"}, {$set:{"personalityType" : ["Navigator","Refiner","Researcher","Supporter","Tough_N_Tender"]}});
db.sPGoal.update({name:"Appreciation"}, {$set:{"personalityType" : ["Examiner","Navigator","Pragmatist","Researcher","Visionary"]}});
db.sPGoal.update({name:"Releasing Control"}, {$set:{"personalityType" : ["Refiner","Tough_N_Tender","Visionary"]}});
db.sPGoal.update({name:"Persuasion"}, {$set:{"personalityType" : ["Researcher"]}});
db.sPGoal.update({name:"Separating Out Emotions"}, {$set:{"personalityType" : ["Actuary","Examiner","Motivator","Refiner"]}});
db.sPGoal.update({name:"Taking Action"}, {$set:{"personalityType" : ["Actuary","Designer","Pragmatist","Refiner"]}});
db.sPGoal.update({name:"Communicating for Results"}, {$set:{"personalityType" : ["Visionary"]}});
db.sPGoal.update({name:"Logic & Rationale"}, {$set:{"personalityType" : ["Ambassador","Promoter"]}});
db.sPGoal.update({name:"Team Building"}, {$set:{"personalityType" : ["Visionary"]}});
db.sPGoal.update({name:"Assertiveness"}, {$set:{"personalityType" : ["Ambassador","Supporter"]}});
db.sPGoal.update({name:"Attention to Detail"}, {$set:{"personalityType" : ["Ambassador","Encourager","Innovator","Instructor","Motivator","Promoter","Supporter"]}});
db.sPGoal.update({name:"Self Awareness"}, {$set:{"personalityType" : ["Supporter"]}});
db.sPGoal.update({name:"Seeking Feedback"}, {$set:{"personalityType" : ["Actuary","Ambassador","Designer","Encourager","Examiner","Innovator","Instructor","Motivator","Navigator","Pragmatist","Promoter","Refiner","Supporter","Tough_N_Tender"]}});
db.sPGoal.update({name:"Speaking Up"}, {$set:{"personalityType" : ["Ambassador","Supporter"]}});
db.sPGoal.update({name:"Focus"}, {$set:{"personalityType" : ["Pragmatist","Promoter"]}});
db.sPGoal.update({name:"Managing Differences"}, {$set:{"personalityType" : ["Actuary","Ambassador","Encourager","Examiner","Motivator","Pragmatist","Researcher","Supporter","Tough_N_Tender","Visionary"]}});
db.sPGoal.update({name:"Receptivity to New Ideas"}, {$set:{"personalityType" : ["Tough_N_Tender"]}});
db.sPGoal.update({name:"Awareness of Others"}, {$set:{"personalityType" : ["Designer","Examiner","Refiner"]}});
db.sPGoal.update({name:"Active Listening"}, {$set:{"personalityType" : ["Encourager","Innovator","Instructor","Motivator","Promoter"]}});
db.sPGoal.update({name:"Speaking with Purpose"}, {$set:{"personalityType" : ["Supporter"]}});
db.sPGoal.update({name:"Patience"}, {$set:{"personalityType" : ["Visionary"]}});
db.sPGoal.update({name:"Presenting Facts"}, {$set:{"personalityType" : ["Promoter"]}});
db.sPGoal.update({name:"Taking Risks"}, {$set:{"personalityType" : ["Designer","Navigator","Pragmatist","Refiner","Supporter"]}});
db.sPGoal.update({name:"Forethought & Planning"}, {$set:{"personalityType" : ["Actuary","Ambassador","Encourager","Innovator","Instructor","Motivator","Promoter","Visionary"]}});
db.sPGoal.update({name:"Satisfaction"}, {$set:{"personalityType" : ["Designer","Navigator","Refiner","Researcher"]}});

