/*
 2015 ReadSpeaker International B.v.
*/
window.ReadSpeakerDefer={deferred:null,clickhandler:function(b){b=b||window.event;var d=b.target||b.srcElement;3===d.nodeType&&(d=d.parentNode);if(d!==document&&window.ReadSpeakerDefer.isRSLink(d))return window.ReadSpeakerDefer.deferred=d,(d=window.ReadSpeakerDefer.findRSParent(d))&&d.className&&!/rsdeferred/i.test(d.className)&&(d.className+=" rsdeferred"),window.ReadSpeakerJIT&&r.loadCore(),b.cancelBubble=!0,b.preventDefault&&b.preventDefault(),b.stopPropagation&&b.stopPropagation(),!1},init:function(){this.RSDeferClick(document)},
isRSLink:function(b){return this.isRSParent(b.parentNode)||b.href&&-1<b.href.indexOf("readspeaker.com/cgi-bin/rsent")},isRSParent:function(b){return b?b.className&&-1<b.className.indexOf("rsbtn")||b.id&&"string"===typeof b.id&&-1<b.id.indexOf("readspeaker_button"):!1},findRSParent:function(b){for(;b.parentNode&&b.parentNode!==document&&(b=b.parentNode,"a"!=b.tagName.toLowerCase()||!this.isRSLink(b)););return b==document?void 0:b.parentNode},RSDeferClick:function(b){b.addEventListener?b.addEventListener("click",
this.clickhandler,!1):b.attachEvent?b.attachEvent("onclick",this.clickhandler):b.onclick=this.clickhandler}};window.ReadSpeakerDefer.init();
(function(b){var d=function(){var f={major:"2",minor:"5",update:"8",revision:"3715",prod:"embhl"},k=[],C=0,p=0,D=!1,q=[],E=0,l=[],F=!1,s=!1,J=0,w=!1,m=null,h="default",G=!1,t=[],H=!1,x="",y={},z=!1,A="",u=null,n=!1,B=function(a){if("string"==typeof a){a="ReadSpeaker."+a.replace("_",".");a=a.split(".");for(var e=b,c=0,v=a.length;c<v;c++)if(e)if(e[a[c]]){if(c==v-1)return e[a[c]];e=e[a[c]]}else break;else break;return!1}},I=function(a,e){q.push(a);E++;e=e||[a];for(var c=0,v=e.length;c<v;c++)try{var d=
B(e[c]);"function"==typeof d.init&&d.init.apply(d,[])}catch(f){_log("[rspkr] Could not load: "+e[c]+" | "+f,3)}E===p&&!0===D&&(_log("[rspkr] All prod mods loaded. _domready = "+w,4),n&&b.ReadSpeaker.init(),c=function(){rspkr.Common.createShortcuts();rspkr.devt("onModsLoaded",b);rspkr.devt("onAfterModsLoaded",b);y.onAdapterReady?rspkr.devt("onReady",b):rspkr.evt("onAdapterReady",function(){rspkr.devt("onReady",b)});b.ReadSpeaker.ui.viewport={width:$rs.width(b),height:$rs.height(b)}},b.ReadSpeaker.Common.addEvent("onReady",
function(){Dispatcher.executeCode();Dispatcher.flush();u&&_startAutoplay()}),w?c():b.ReadSpeaker.Common.addEvent("onDOMReady",c))},L=function(){var a={id:"",type:"text/javascript",src:"",cb:function(){var a=(b.event&&b.event.srcElement&&b.event.srcElement.id?b.event.srcElement.id:this.id).replace("rsmod_","");q.push(a);a=B(a);"function"==typeof a.init&&a.init.apply(a,[]);K()}},e=b.ReadSpeaker.lib.Facade.currentLib().toLowerCase();"rslib"==e?(a.id="rsmod_lib.RSLib",a.src="ReadSpeaker.lib.RSLib.js"):
(a.id="rsmod_lib.Facade.adapter."+e,a.src="ReadSpeaker.lib.Facade.adapter."+e+".js");RSLoad.load(a)},K=function(){if(H&&b.ReadSpeaker.modmap&&!F){for(var a=b.ReadSpeaker.modmap,e=[],c=0,d="|",f=[],h=0,k=t.length;h<k;h++)if(e=a.products&&"function"==typeof a.products[t[h]]?a.products[t[h]]():null){for(var g=c=0,l=e.length;g<l;g++)-1===d.indexOf("|"+e[g][0]+e[g][1]+"|")&&(e[g][0].length&&(f[e[g][0]]=e[g][2],/text\/javascript/.test(e[g][1])&&(cb=function(){var a=(b.event&&b.event.srcElement&&b.event.srcElement.id?
b.event.srcElement.id:this.id).replace("rsmod_","");I(a,f[a])}),RSLoad.load({id:"rsmod_"+e[g][0],type:e[g][1],src:"ReadSpeaker."+e[g][0]+("text/css"===e[g][1]?".css":".js"),cb:cb,async:!0})),"undefined"!==typeof e[g][1]&&/text\/javascript/.test(e[g][1])&&c++,d+=e[g][0]+e[g][1]+"|");p+=c}D=!0}};Constructor=function(){if(b.rsConf&&b.rsConf.params&&"string"===typeof b.rsConf.params&&b.rsConf.params)var a=b.rsConf.params,e=a.split("?");else e=document.getElementsByTagName("script"),a=e[e.length-1].getAttribute("src"),
e=a.split("?");/\?/i.test(a)&&1<e.length&&e[1].length?(A=a.replace(/[^\/]*$/,""),x=_getDebugLevel(),m=a=Params.extract(e[1]),h=a.skin||"default",t=a.pids.split(","),m.path=e[0].replace("ReadSpeaker.js",""),k.Core=["Common","lib.Facade","modmap"],k["pub.Config"]=!1,u=a.autoplay,n=b.ReadSpeakerJIT="1"===a.jit,m.forceBasicMode&&"1"===m.forceBasicMode||document.attachEvent&&/MSIE/i.test(navigator.userAgent)&&(document.compatMode&&"backcompat"===document.compatMode.toLowerCase()||/MSIE 6\./i.test(navigator.userAgent))?
(z=!0,RSLoad.load({id:"rsmod_Styles",type:"text/css",src:(m.skinPathBasic||"ReadSpeaker.Styles-Basic")+".css",cb:null})):(RSLoad.load({id:"rsmod_Styles",type:"text/css",src:"ReadSpeaker.Styles"+(n?"-Button":"")+".css",cb:null}),"default"===h||n||(p++,RSLoad.load({id:"rsskin_"+h+"_style",type:"text/css",src:"skins/"+h+"/"+h+".css",cb:null}),RSLoad.load({id:"rsskin_"+h+"_js",type:"text/javascript",src:"skins/"+h+"/"+h+".js",cb:function(){"default"!==h&&s?_updateBaseClass():G=!0},async:!0}))),n||_loadCore()):
F=!0};_loadCore=function(){if(!s){n&&!z&&(document.getElementById("rsmod_Styles").href=A+"ReadSpeaker.Styles.css");for(var a in k)k.hasOwnProperty(a)&&(mod=a,RSLoad.load({id:"req_"+mod,type:"text/javascript",src:"ReadSpeaker."+mod+".js",cb:function(){var a=(b.event&&b.event.srcElement&&b.event.srcElement.id?b.event.srcElement.id:this.id).replace("req_",""),a=a.replace("_","."),a=!1===k[a]?[a]:k[a],c;C++;for(var d=0,f=a.length;d<f;d++)q.push(a[d]),c=B(a[d]),"function"==typeof c.init&&c.init.apply(c,
[]);C===Object.size(k)&&(b.ReadSpeaker.Common.addEvent("onModsLoaded",b.ReadSpeaker.pub.Config.setup),H=!0,L())},async:!0}))}};_updateBaseClass=function(){rspkr.log("[rspkr.updateBaseClass] Attempting to update..");for(var a=document.getElementsByTagName("div"),e=/\brsbtn\b/,c=0,d=a.length;c<d;c++)e.test(a[c].className)&&(a[c].className=a[c].className.replace(e,b.rsConf.ui.rsbtnClass));rspkr.log("[rspkr.updateBaseClass] Update successful!");I("skinfile")};Utils=function(){Object.size=function(a){var b=
0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b}};Params={extract:function(a){if("string"==typeof a){var b={};a=a.split(/[;&]/);for(var c,d=0;d<a.length;d++)(c=a[d].split("="))&&2==c.length&&(b[unescape(c[0])]=unescape(c[1]).replace(/\+/g," "));return b}return{}}};Dispatcher={isok:!0,executeCode:function(){this.isok=!0;if(!l.length)return!0;for(idx in l)if(l.hasOwnProperty(idx)&&"function"==typeof l[idx])try{l[idx].apply(b,[])}catch(a){this.isok=!1,rspkr.log("[rspkr.q] "+a,3)}},flush:function(){l=
[]}};RSLoad={load:function(a){if("text/javascript"==a.type||"text/css"==a.type){a.src=m.path+a.src;var e=document.getElementsByTagName("head")[0],c=document.createElement("text/javascript"==a.type?"script":"link"),d=[f.major,f.minor,f.update,f.revision].join(".");"function"==typeof a.cb&&(void 0!==c.onreadystatechange?c.onreadystatechange=function(){"complete"!=this.readyState&&"loaded"!=this.readyState||a.cb.apply(b)}:c.onload=a.cb);c.id=a.id.replace(".","_");c.type=a.type;"text/javascript"==a.type?
(c.src=a.src+"?v="+d,a.async&&(c.async=!0)):(c.rel="stylesheet",c.href=a.src+"?v="+d);e.appendChild(c)}}};_getID=function(){return"readspeaker"+J++};_getExternalRef=function(a,b){return{id:b[1]||_getID(),type:b[2]||"text/javascript",src:a,cb:b[3]||null}};_logcount=0;_errorlog={1:[],2:[],3:[],4:[],5:[],6:[]};_showLog=function(a){rspkr.log("[rspkr.printErrorLog]",1);a=(a||"3").split(",");for(var b=0;b<a.length;b++)_errorlog.hasOwnProperty(a[b])&&_formatLog(_errorlog[a[b]],a[b])};_formatLog=function(a,
b){b=parseInt(b)||3;var c=_levelMap[b].lbl;console.groupCollapsed&&console.groupCollapsed(c);for(c=0;c<a.length;c++)try{console[_levelMap[b].method]&&console[_levelMap[b].method](a[c])}catch(d){}console.groupCollapsed&&console.groupEnd()};_levelMap={1:{lbl:"Info",method:"log"},2:{lbl:"Warn",method:"warn"},3:{lbl:"Err",method:"error"},4:{lbl:"AS",method:"log"},5:{lbl:"SW",method:"log"}};_log=function(a,b){var c=x;b=b||1;_errorlog[b].push(a);if(c&&"string"===typeof c&&-1<c.indexOf(","+b+",")){c=_levelMap[b].lbl;
try{console[_levelMap[b].method]&&console[_levelMap[b].method](_logcount++ +". "+c+": "+a)}catch(d){}}};_getDebugLevel=function(){var a;if(/rsdebug=rsdebug/i.test(document.location.href))try{a=","+document.location.href.split("?").pop().match(/rsdebug=rsdebug([^$|&]*)/i).pop()+","}catch(b){a=",3,"}else a="";return a};_setDebugLevel=function(a){x=/^,[0-9,]*,$/.test(a)?a:","+a+","};_startAutoplay=function(){rspkr.log("[rspkr.startAutoplay] Id: "+u);var a=$rs.get(u);if($rs.isArray(a)&&0<a.length)a=a[0];
else if($rs.isArray(a)&&0==a.length)return!1;a=$rs.findIn(a,"a");if($rs.isArray(a)&&0<a.length)a=a[0];else if($rs.isArray(a)&&0==a.length)return!1;b.readpage(a)};d=function(){this.meta={obj:f,version:[f.major,f.minor,f.update].join(".")+"_rev"+f.revision+"-"+f.prod};this.q=function(a){"function"==typeof a&&(y.onReady?a.apply(b,[]):l.push(a))};this.init=function(){s||(s=!0,document.addEventListener&&document.removeEventListener("DOMContentLoaded",b.ReadSpeaker.init,!1),w=!0,b.ReadSpeaker.Common&&b.ReadSpeaker.Common.dispatchEvent("onDOMReady"),
_log("[rspkr] DOM Ready!"),G&&(_log("[rspkr] Updating base class.",1),_updateBaseClass()))};this.getLoadedMods=function(){return q};this.rsidCount=1E3;this.logcount=0;this.log=function(a,b){_log(a,b||1)};this.showLog=function(a){_showLog(a||"1")};this.getID=function(){return _getID()};this.getVersion=function(){return this.meta.version};this.skin=h;this.displog=y;this.basicMode=z;this.params=m;this.setDebugLevel=_setDebugLevel;this.baseUrl=A;this.loadCore=_loadCore;this.audio=null};Utils();Constructor();
return new d}();b.ReadSpeaker=b.rs=b.rspkr=d})(window);ReadSpeaker.enums={mime:{tjs:"text/javascript",tcss:"text/css",thtml:"text/html"}};
(function(b){if(!window.ReadSpeakerJIT){var d=navigator.userAgent,f=/*@cc_on!@*/false,k=setTimeout;/mozilla/i.test(d)&&!/(compati)/.test(d)||/opera/i.test(d)||/webkit/i.test(d)?document.addEventListener("DOMContentLoaded",b,!1):f?function(){var d=document.createElement("doc:rdy");try{d.doScroll("left"),b()}catch(f){k(arguments.callee,0)}}():window.onload=b}})(ReadSpeaker.init);
