ReadSpeaker.lib||(ReadSpeaker.lib={});
(function(z,I){function v(r,a,f,d){for(var c=0,m=a.length;c<m;c++)k(r,a[c],f,d)}function a(r,a,f,d,c,m){var e,n=l.setFilters[a.toLowerCase()];n||k.error(a);!r&&(e=c)||v(r||"*",d,e=[],c);return 0<e.length?n(e,f,m):[]}function c(r,b,f,d,c){for(var m,e,n,h,g,l,q,p=0,u=c.length,s=B.POS,x=new RegExp("^"+s.source+"(?![\\x20\\t\\r\\n\\f])","i"),y=function(){for(var r=1,a=arguments.length-2;r<a;r++)arguments[r]===I&&(m[r]=I)};p<u;p++){s.exec("");r=c[p];h=[];n=0;for(g=d;m=s.exec(r);)if(e=s.lastIndex=m.index+
m[0].length,e>n){q=r.slice(n,m.index);n=e;l=[b];L.test(q)&&(g&&(l=g),g=d);if(e=da.test(q))q=q.slice(0,-5).replace(L,"$&*");1<m.length&&m[0].replace(x,y);g=a(q,m[1],m[2],l,g,e)}g?(h=h.concat(g),(q=r.slice(n))&&")"!==q?L.test(q)?v(q,h,f,d):k(q,b,f,d?d.concat(g):g):G.apply(f,h)):k(r,b,f,d)}return 1===u?f:k.uniqueSort(f)}function d(r,a,f){var d=a.dir,c=Y++;r||(r=function(r){return r===f});return a.first?function(a,b){for(;a=a[d];)if(1===a.nodeType)return r(a,b)&&a}:function(a,b){for(var f,e=c+"."+p,g=
e+"."+h;a=a[d];)if(1===a.nodeType){if((f=a[s])===g)return a.sizset;if("string"===typeof f&&0===f.indexOf(e)){if(a.sizset)return a}else{a[s]=g;if(r(a,b))return a.sizset=!0,a;a.sizset=!1}}}}function e(a,b){return a?function(f,d){var c=b(f,d);return c&&a(!0===c?f:c,d)}:b}function g(a){return function(b,f){for(var d,c=0;d=a[c];c++)if(d(b,f))return!0;return!1}}var h,p,M,K,E,x=z.document,u=x.documentElement,N=!1,Z=!0,Y=0,C=[].slice,G=[].push,s=("sizcache"+Math.random()).replace(".",""),F="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+
"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w#")+")|)|)[\\x20\\t\\r\\n\\f]*\\]",y="(?=[^\\x20\\t\\r\\n\\f])(?:\\\\.|"+F+"|"+":((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|((?:[^,]|\\\\,|(?:,(?=[^\\[]*\\]))|(?:,(?=[^\\(]*\\))))*))\\)|)".replace(2,7)+"|[^\\\\(),])+",O=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),L=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,P=new RegExp(y+"?(?=[\\x20\\t\\r\\n\\f]*,|$)","g"),$=new RegExp("^(?:(?!,)(?:(?:^|,)[\\x20\\t\\r\\n\\f]*"+
y+")*?|[\\x20\\t\\r\\n\\f]*(.*?))(\\)|$)"),ea=new RegExp(y.slice(19,-6)+"\\x20\\t\\r\\n\\f>+~])+|[\\x20\\t\\r\\n\\f]*([\\x20\\t\\r\\n\\f>+~])[\\x20\\t\\r\\n\\f]*","g"),fa=/^(?:#([\w\-]+)|(\w+)|\.([\w\-]+))$/,Q=/[\x20\t\r\n\f]*[+~]/,da=/:not\($/,ga=/h\d/i,ha=/input|select|textarea|button/i,H=/\\(?!\\)/g,B={ID:/^#((?:\\.|[-\w]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[-\w]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[-\w]|[^\x00-\xa0])+)['"]?\]/,TAG:new RegExp("^("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("[-",
"[-\\*")+")"),ATTR:new RegExp("^"+F),PSEUDO:/^:((?:\\.|[-\w]|[^\x00-\xa0])+)(?:\((?:(['"])((?:\\.|[^\\])*?)\2|((?:[^,]|\\,|(?:,(?=[^\[]*\]))|(?:,(?=[^\(]*\))))*))\)|)/,CHILD:/^:(only|nth|last|first)-child(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,POS:RegExp(":(nth|eq|gt|lt|first|last|even|odd)(?:\\((\\d*)\\)|)(?=[^-]|$)","ig"),needsContext:/^[\x20\t\r\n\f]*[>+~]|:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\)|)(?=[^-]|$)/i},
R={},S=[],T={},U=[],F=function(a){a.sizzleFilter=!0;return a},y=function(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}},aa=function(a){return function(b){var f=b.nodeName.toLowerCase();return("input"===f||"button"===f)&&b.type===a}},D=function(a){var b=!1,f=x.createElement("div");try{b=a(f)}catch(d){}return b},ia=D(function(a){a.innerHTML="<select></select>";a=typeof a.lastChild.getAttribute("multiple");return"boolean"!==a&&"string"!==a}),ja=D(function(a){a.id=s+0;a.innerHTML=
"<a name='"+s+"'></a><div name='"+s+"'></div>";u.insertBefore(a,u.firstChild);var b=x.getElementsByName&&x.getElementsByName(s).length===2+x.getElementsByName(s+0).length;E=!x.getElementById(s);u.removeChild(a);return b}),ka=D(function(a){a.appendChild(x.createComment(""));return 0===a.getElementsByTagName("*").length}),la=D(function(a){a.innerHTML="<a href='#'></a>";return a.firstChild&&"undefined"!==typeof a.firstChild.getAttribute&&"#"===a.firstChild.getAttribute("href")}),ba=D(function(a){a.innerHTML=
"<div class='hidden e'></div><div class='hidden'></div>";if(!a.getElementsByClassName||0===a.getElementsByClassName("e").length)return!1;a.lastChild.className="e";return 1!==a.getElementsByClassName("e").length}),k=function(a,b,f,d){f=f||[];b=b||x;var c,e,h,n,g=b.nodeType;if(1!==g&&9!==g)return[];if(!a||"string"!==typeof a)return f;h=V(b);if(!h&&!d&&(c=fa.exec(a)))if(n=c[1])if(9===g)if((e=b.getElementById(n))&&e.parentNode){if(e.id===n)return f.push(e),f}else return f;else{if(b.ownerDocument&&(e=
b.ownerDocument.getElementById(n))&&ma(b,e)&&e.id===n)return f.push(e),f}else{if(c[2])return G.apply(f,C.call(b.getElementsByTagName(a),0)),f;if((n=c[3])&&ba&&b.getElementsByClassName)return G.apply(f,C.call(b.getElementsByClassName(n),0)),f}return W(a,b,f,d,h)},l=k.selectors={cacheLength:50,match:B,order:["ID","TAG"],attrHandle:{},createPseudo:F,find:{ID:E?function(a,b,f){if("undefined"!==typeof b.getElementById&&!f)return(a=b.getElementById(a))&&a.parentNode?[a]:[]}:function(a,b,f){if("undefined"!==
typeof b.getElementById&&!f)return(b=b.getElementById(a))?b.id===a||"undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id").value===a?[b]:I:[]},TAG:ka?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a)}:function(a,b){var f=b.getElementsByTagName(a);if("*"===a){for(var d,c=[],e=0;d=f[e];e++)1===d.nodeType&&c.push(d);return c}return f}},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},
preFilter:{ATTR:function(a){a[1]=a[1].replace(H,"");a[3]=(a[4]||a[5]||"").replace(H,"");"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1]?(a[2]||k.error(a[0]),a[3]=+(a[3]?a[4]+(a[5]||1):2*("even"===a[2]||"odd"===a[2])),a[4]=+(a[6]+a[7]||"odd"===a[2])):a[2]&&k.error(a[0]);return a},PSEUDO:function(a){var b,f=a[4];if(B.CHILD.test(a[0]))return null;f&&(b=$.exec(f))&&b.pop()&&(a[0]=a[0].slice(0,b[0].length-f.length-1),f=b[0].slice(0,-1));a.splice(2,
3,f||a[3]);return a}},filter:{ID:E?function(a){a=a.replace(H,"");return function(b){return b.getAttribute("id")===a}}:function(a){a=a.replace(H,"");return function(b){return(b="undefined"!==typeof b.getAttributeNode&&b.getAttributeNode("id"))&&b.value===a}},TAG:function(a){if("*"===a)return function(){return!0};a=a.replace(H,"").toLowerCase();return function(b){return b.nodeName&&b.nodeName.toLowerCase()===a}},CLASS:function(a){var b=R[a];b||(b=R[a]=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),
S.push(a),S.length>l.cacheLength&&delete R[S.shift()]);return function(a){return b.test(a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}},ATTR:function(a,b,f){return b?function(d){d=k.attr(d,a);var c=d+"";if(null==d)return"!="===b;switch(b){case "=":return c===f;case "!=":return c!==f;case "^=":return f&&0===c.indexOf(f);case "*=":return f&&-1<c.indexOf(f);case "$=":return f&&c.substr(c.length-f.length)===f;case "~=":return-1<(" "+c+" ").indexOf(f);case "|=":return c===
f||c.substr(0,f.length+1)===f+"-"}}:function(b){return null!=k.attr(b,a)}},CHILD:function(a,b,f,d){if("nth"===a){var c=Y++;return function(a){var b,r=0,e=a;if(1===f&&0===d)return!0;if((b=a.parentNode)&&(b[s]!==c||!a.sizset)){for(e=b.firstChild;e&&(1!==e.nodeType||(e.sizset=++r,e!==a));e=e.nextSibling);b[s]=c}a=a.sizset-d;return 0===f?0===a:0===a%f&&0<=a/f}}return function(b){var f=b;switch(a){case "only":case "first":for(;f=f.previousSibling;)if(1===f.nodeType)return!1;if("first"===a)return!0;f=b;
case "last":for(;f=f.nextSibling;)if(1===f.nodeType)return!1;return!0}}},PSEUDO:function(a,b,f,d){var c=l.pseudos[a]||l.pseudos[a.toLowerCase()];c||k.error("unsupported pseudo: "+a);return c.sizzleFilter?c(b,f,d):c}},pseudos:{not:F(function(a,b,f){var c=ca(a.replace(O,"$1"),b,f);return function(a){return!c(a)}}),enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},
selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},parent:function(a){return!l.pseudos.empty(a)},empty:function(a){var b;for(a=a.firstChild;a;){if("@"<a.nodeName||3===(b=a.nodeType)||4===b)return!1;a=a.nextSibling}return!0},contains:F(function(a){return function(b){return-1<(b.textContent||b.innerText||X(b)).indexOf(a)}}),has:F(function(a){return function(b){return 0<k(a,b).length}}),header:function(a){return ga.test(a.nodeName)},text:function(a){var b,f;return"input"===
a.nodeName.toLowerCase()&&"text"===(b=a.type)&&(null==(f=a.getAttribute("type"))||f.toLowerCase()===b)},radio:y("radio"),checkbox:y("checkbox"),file:y("file"),password:y("password"),image:y("image"),submit:aa("submit"),reset:aa("reset"),button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},input:function(a){return ha.test(a.nodeName)},focus:function(a){var b=a.ownerDocument;return a===b.activeElement&&(!b.hasFocus||b.hasFocus())&&!(!a.type&&!a.href)},
active:function(a){return a===a.ownerDocument.activeElement}},setFilters:{first:function(a,b,f){return f?a.slice(1):[a[0]]},last:function(a,b,f){b=a.pop();return f?a:[b]},even:function(a,b,f){b=[];f=f?1:0;for(var c=a.length;f<c;f+=2)b.push(a[f]);return b},odd:function(a,b,f){b=[];f=f?0:1;for(var c=a.length;f<c;f+=2)b.push(a[f]);return b},lt:function(a,b,f){return f?a.slice(+b):a.slice(0,+b)},gt:function(a,b,f){return f?a.slice(0,+b+1):a.slice(+b+1)},eq:function(a,b,f){b=a.splice(+b,1);return f?a:
b}}};l.setFilters.nth=l.setFilters.eq;l.filters=l.pseudos;la||(l.attrHandle={href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}});ja&&(l.order.push("NAME"),l.find.NAME=function(a,b){if("undefined"!==typeof b.getElementsByName)return b.getElementsByName(a)});ba&&(l.order.splice(1,0,"CLASS"),l.find.CLASS=function(a,b,f){if("undefined"!==typeof b.getElementsByClassName&&!f)return b.getElementsByClassName(a)});try{C.call(u.childNodes,0)[0].nodeType}catch(na){C=
function(a){for(var b,f=[];b=this[a];a++)f.push(b);return f}}var V=k.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1},ma=k.contains=u.compareDocumentPosition?function(a,b){return!!(a.compareDocumentPosition(b)&16)}:u.contains?function(a,b){var f=9===a.nodeType?a.documentElement:a,c=b.parentNode;return a===c||!!(c&&1===c.nodeType&&f.contains&&f.contains(c))}:function(a,b){for(;b=b.parentNode;)if(b===a)return!0;return!1},X=k.getText=function(a){var b,c="",
d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=X(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d];d++)c+=X(b);return c};k.attr=function(a,b){var c;(c=V(a))||(b=b.toLowerCase());return l.attrHandle[b]?l.attrHandle[b](a):ia||c?a.getAttribute(b):(c=a.getAttributeNode(b))?"boolean"===typeof a[b]?a[b]?b:null:c.specified?c.value:null:null};k.error=function(a){throw Error("Syntax error, unrecognized expression: "+
a);};[0,0].sort(function(){return Z=0});u.compareDocumentPosition?M=function(a,b){return a===b?(N=!0,0):(a.compareDocumentPosition&&b.compareDocumentPosition?a.compareDocumentPosition(b)&4:a.compareDocumentPosition)?-1:1}:(M=function(a,b){if(a===b)return N=!0,0;if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-b.sourceIndex;var c,d,e=[],h=[];c=a.parentNode;d=b.parentNode;var g=c;if(c===d)return K(a,b);if(!c)return-1;if(!d)return 1;for(;g;)e.unshift(g),g=g.parentNode;for(g=d;g;)h.unshift(g),g=g.parentNode;
c=e.length;d=h.length;for(g=0;g<c&&g<d;g++)if(e[g]!==h[g])return K(e[g],h[g]);return g===c?K(a,h[g],-1):K(e[g],b,1)},K=function(a,b,c){if(a===b)return c;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1});k.uniqueSort=function(a){var b,c=1;if(M&&(N=Z,a.sort(M),N))for(;b=a[c];c++)b===a[c-1]&&a.splice(c--,1);return a};var ca=k.compile=function(a,b,c){var h,A,m=T[a];if(m&&m.context===b)return m;var J,n,m=[];h=0;for(var t=$.exec(a),w=!t.pop()&&!t.pop(),p=w&&a.match(P)||[""],q=l.preFilter,
s=l.filter,u=!c&&b!==x;null!=(n=p[h])&&w;h++)for(m.push(J=[]),u&&(n=" "+n);n;){w=!1;if(t=L.exec(n))n=n.slice(t[0].length),w=J.push({part:t.pop().replace(O," "),captures:t});for(A in s)!(t=B[A].exec(n))||q[A]&&!(t=q[A](t,b,c))||(n=n.slice(t.shift().length),w=J.push({part:A,captures:t}));if(!w)break}w||k.error(a);for(A=0;h=m[A];A++){J=m;n=A;t=b;w=c;q=p=void 0;for(s=0;p=h[s];s++)l.relative[p.part]?q=d(q,l.relative[p.part],t):(p.captures.push(t,w),q=e(q,l.filter[p.part].apply(null,p.captures)));J[n]=
q}m=T[a]=g(m);m.context=b;m.runs=m.dirruns=0;U.push(a);U.length>l.cacheLength&&delete T[U.shift()];return m};k.matches=function(a,b){return k(a,null,null,b)};k.matchesSelector=function(a,b){return 0<k(b,null,null,[a]).length};var W=function(a,b,d,e,g){a=a.replace(O,"$1");var m,k,n,t,w,s,q=a.match(P);k=a.match(ea);n=b.nodeType;if(B.POS.test(a))return c(a,b,d,e,q);if(e)m=C.call(e,0);else if(q&&1===q.length){if(1<k.length&&9===n&&!g&&(q=B.ID.exec(k[0]))){b=l.find.ID(q[1],b,g)[0];if(!b)return d;a=a.slice(k.shift().length)}e=
(q=Q.exec(k[0]))&&!q.index&&b.parentNode||b;s=k.pop();t=s.split(":not")[0];k=0;for(n=l.order.length;k<n;k++)if(w=l.order[k],q=B[w].exec(t))if(m=l.find[w]((q[1]||"").replace(H,""),e,g),null!=m){t===s&&((a=a.slice(0,a.length-s.length)+t.replace(B[w],""))||G.apply(d,C.call(m,0)));break}}if(a)for(g=ca(a,b,g),p=g.dirruns++,null==m&&(m=l.find.TAG("*",Q.test(a)&&b.parentNode||b)),k=0;a=m[k];k++)h=g.runs++,g(a,b)&&d.push(a);return d};x.querySelectorAll&&function(){var a,b=W,c=/'|\\/g,d=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,
e=[],g=[":active"],h=u.matchesSelector||u.mozMatchesSelector||u.webkitMatchesSelector||u.oMatchesSelector||u.msMatchesSelector;D(function(a){a.innerHTML="<select><option selected></option></select>";a.querySelectorAll("[selected]").length||e.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||e.push(":checked")});D(function(a){a.innerHTML="<p test=''></p>";a.querySelectorAll("[test^='']").length&&e.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");
a.innerHTML="<input type='hidden'>";a.querySelectorAll(":enabled").length||e.push(":enabled",":disabled")});e=e.length&&new RegExp(e.join("|"));W=function(a,d,g,h,k){if(!(h||k||e&&e.test(a)))if(9===d.nodeType)try{return G.apply(g,C.call(d.querySelectorAll(a),0)),g}catch(m){}else if(1===d.nodeType&&"object"!==d.nodeName.toLowerCase()){var l=d.getAttribute("id"),p=l||s,r=Q.test(a)&&d.parentNode||d;l?p=p.replace(c,"\\$&"):d.setAttribute("id",p);try{return G.apply(g,C.call(r.querySelectorAll(a.replace(P,
"[id='"+p+"'] $&")),0)),g}catch(u){}finally{l||d.removeAttribute("id")}}return b(a,d,g,h,k)};h&&(D(function(b){a=h.call(b,"div");try{h.call(b,"[test!='']:sizzle"),g.push(l.match.PSEUDO.source,l.match.POS.source,"!=")}catch(c){}}),g=new RegExp(g.join("|")),k.matchesSelector=function(b,c){c=c.replace(d,"='$1']");if(!(V(b)||g.test(c)||e&&e.test(c)))try{var f=h.call(b,c);if(f||a||b.document&&11!==b.document.nodeType)return f}catch(l){}return 0<k(c,null,null,[b]).length})}();z.ReadSpeaker.Sizzle=k})(window);
ReadSpeaker.lib.RSLib=function(){var z={core_pnum:function(){return/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source},rposition:function(){return/^(top|right|bottom|left)$/},rmargin:function(){return/^margin/},rnumsplit:function(){return new RegExp("^("+this.core_pnum+")(.*)$","i")},rnumnonpx:function(){return new RegExp("^("+this.core_pnum+")(?!px)[a-z%]+$","i")},rmsPrefix:function(){return/^-ms-/},rdashAlpha:function(){return/-([\da-z])/gi}},I={_formatRet:function(a){return a.length?1==a.length?a[0].length&&
"object"===typeof a[0]&&!a[0].tagName?a[0][0]:a[0]:a:[]},get:function(a){return"#"===a?[]:"object"==typeof a?a:document.getElementById(a)||this._formatRet(window.ReadSpeaker.Sizzle(a))},findIn:function(a,c){"string"===typeof a&&(a=this.get(a));return this._formatRet(window.ReadSpeaker.Sizzle(c,a))},closest:function(a,c){var d=!1,e=null,g=null,e=null,h=a;"string"===typeof a&&(h=this.get(a));e=$rs.findIn(h.parentNode,c);if(e===h)return h;for(;!d&&h!==document.body;){g=h.parentNode;e=h.parentNode.parentNode;
if((e=$rs.findIn(e,c))&&e===g){d=!0;break}else if(e&&$rs.isArray(e)&&e.length)for(var h=0,p=e.length;h<p;h++)if(e[h]&&e[h]===g){d=!0;e=e[h];break}h=g}if(d)return e},getAttr:function(a,c){"string"===typeof a&&(a=this.get(a));if("style"===c)return a.style.cssText.toLowerCase()||void 0;if(a.getAttribute)return a.getAttribute(c);if(a[c])return a[c]},setAttr:function(a,c,d){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var e=0,g=a.length;e<g;e++)"style"===c?a[e].style.cssText=d:a[e].setAttribute?
a[e].setAttribute(c,d):a[e][c]=d;return d},regEvent:function(a,c,d){var e,g;"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var h=0,p=a.length;h<p;h++)g=a[h].window?document.documentElement:a[h],e=this.getAttr(g,"data-rsevent-id")||"rs_"+Math.round(1E6*Math.random()),this.setAttr(g,"data-rsevent-id",e),v.push(e,c,d),v.store[e]&&v.store[e][c]&&1<v.store[e][c].length||_addEvent(a[h],c,v.dispatch)},unregEvent:function(a,c,d){if(a){var e;"string"===typeof a&&(a=this.get(a));this.isArray(a)||
(a=[a]);for(var g=0,h=a.length;g<h;g++)if(e=a[g].window?document.documentElement:a[g],e=this.getAttr(e,"data-rsevent-id"),d)(e=v.pop(e,c,d))||_removeEvent(a[g],c,v.dispatch);else if(_removeEvent(a[g],c,v.dispatch),e&&c){v.store[e][c]=void 0;try{delete v.store[e][c]}catch(p){}}}},fireEvent:function(a,c){return!1},width:function(a){"string"===typeof a&&(a=this.get(a));return _getSize(a,"width")},height:function(a){"string"===typeof a&&(a=this.get(a));return _getSize(a,"height")},innerWidth:function(a){"string"===
typeof a&&(a=this.get(a));var c=parseFloat(_getCss(a,"border-left-width"))+parseFloat(_getCss(a,"border-right-width"));return _getSize(a,"width")-c},innerHeight:function(a){"string"===typeof a&&(a=this.get(a));var c=parseFloat(_getCss(a,"border-top-width"))+parseFloat(_getCss(a,"border-bottom-width"));return _getSize(a,"height")-c},outerWidth:function(a,c){"string"===typeof a&&(a=this.get(a));if(a&&a.style){var d=c?parseFloat(_getCss(a,"margin-left"))+parseFloat(_getCss(a,"margin-right")):0;return _getSize(a,
"width")+d}return null},outerHeight:function(a,c){"string"===typeof a&&(a=this.get(a));if(a&&a.style){var d=c?parseFloat(_getCss(a,"margin-top"))+parseFloat(_getCss(a,"margin-bottom")):0;return _getSize(a,"height")+d}return null},offsetParent:function(a){"string"===typeof a&&(a=this.get(a));for(var c=/absolute|relative|fixed/i;a!==document.body&&(a=a.parentNode,!a.style||!c.test(_getCss(a,"position"))););return a||document.body},offset:function(a,c){"string"===typeof a&&(a=this.get(a));var d=document.body,
e=document.defaultView||window,g=document.documentElement,h=document.createElement("div");if(a===document.body){var h=d.offsetTop,p=d.offsetLeft;/explorer/i.test(rspkr.c.data.browser.name)&&8>rspkr.c.data.browser.version||(h+=parseFloat(_getCss(d,"marginTop"))||0,p+=parseFloat(_getCss(d,"marginLeft"))||0);return{top:h,left:p}}h.style.paddingLeft=h.style.width="1px";d.appendChild(h);var v=2==h.offsetWidth;d.removeChild(h);var h=a.getBoundingClientRect(),p=g.clientTop||d.clientTop||0,z=g.clientLeft||
d.clientLeft||0,E=e.pageYOffset||v&&g.scrollTop||d.scrollTop,e=e.pageXOffset||v&&g.scrollLeft||d.scrollLeft;rspkr.basicMode&&a===d&&E&&!h.top&&(h.top=-E);rspkr.basicMode&&a===d&&e&&!h.left&&(h.left=-e);return{top:h.top+E-p,left:h.left+e-z}},absOffset:function(a){return this.offset(a)},position:function(a){"string"===typeof a&&this.get(a);return!1},scrollLeft:function(a,c){"string"===typeof a&&(a=this.get(a));return _scrollXY("scrollLeft","pageXOffset",a,c)},scrollTop:function(a,c){"string"===typeof a&&
(a=this.get(a));return _scrollXY("scrollTop","pageYOffset",a,c)},addClass:function(a,c){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var d,e=0,g=a.length;e<g;e++)d=_trim(a[e].className+" "+c).replace(/ {2,}/g," ").split(" "),a[e].className=d.join(" ")},removeClass:function(a,c){if(a){"string"===typeof a&&(a=this.get(a));this.isArray(a)||(a=[a]);for(var d,e=0,g=a.length;e<g;e++){d=_trim(c).replace(/ {2,}/g," ");newClassName=_trim(a[e].className);this.isArray(d)||(d=d.split(" "));
for(var h=0,p=d.length;h<p;h++)newClassName=newClassName.replace(new RegExp("\\b"+d[h]+"\\b","gi"),"");a[e].className=_trim(newClassName).replace(/ {2,}/g," ")}}},hasClass:function(a,c){"string"===typeof a&&(a=this.get(a));if(!a||this.isArray(a)&&!a.length)return!1;for(var d=a.className.split(" "),e=0,g=d.length;e<g;e++)if(d[e]==c)return!0;return!1},css:function(a,c,d){"string"===typeof a&&(a=this.get(a));if("object"==typeof c||d){var e={};"string"===typeof c?e[_camelCase(c)]=d:e=c;for(var g in e)e.hasOwnProperty(g)&&
(a.style[_camelCase(g)]=e[g])}else return _getCss(a,_camelCase(c))},isVisible:function(a){for(;a!==document.body;){if("none"===this.css(a,"display"))return!1;a=a.parentNode}return!0},addStyleRule:function(a,c,d){d="string"==typeof d?document.styleSheets[d]||document.getElementById(d):d;d.addRule?d.addRule(a,c):d.sheet.insertRule&&d.sheet.insertRule(a+" {"+c+"}",d.sheet.cssRules.length)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},rsid:function(a){if(""==this.getAttr(a,
"data-rsid")||void 0==this.getAttr(a,"data-rsid")){var c=ReadSpeaker.rsidCount++;this.setAttr(a,"data-rsid",c)}return this.getAttr(a,"data-rsid")},detach:function(a){return a.parentNode.removeChild(a)},convertEvent:function(a,c){a=a||window.event;var d=new ReadSpeaker.lib.Facade.RSEvent;d.pageX=a.pageX||a.clientX+$rs.scrollLeft(document);d.pageY=a.pageY||a.clientY+$rs.scrollTop(document);d.screenX=a.screenX;d.screenY=a.screenY;d.clientX=a.clientX;d.clientY=a.clientY;d.target=a.currentTarget||c;d.type=
a.type;d.keyCode=a.keyCode;d.targetTouches=a.targetTouches;d.originalEvent=a;return d},clone:function(a,c,d){return a.cloneNode(d||!1)},camel:function(a){return _camelCase(a)},remove:function(a){return jQuery(elm).remove()},replaceWith:function(a,c){return _formatRet(jQuery(a).replaceWith(c))},focus:function(a,c){void 0!==c?this.focusIn(a,c):(a=this.get(a),this.isArray(a)&&0<a.length?a[0].focus?a[0].focus():a[0].setActive&&a[0].setActive():a.focus?a.focus():a.setActive&&a.setActive())},focusIn:function(a,
c){a=this.get(a);if(this.isArray(a)&&0<a.length)for(var d=0;d<a.length;d++)void 0!==c&&_addEvent(a[d],"focus",c);else void 0!==c&&_addEvent(a,"focus",c)},focusOut:function(a,c){a=this.get(a);if(this.isArray(a)&&0<a.length)for(var d=0;d<a.length;d++)void 0!==c&&_addEvent(a[d],"blur",c);else void 0!==c&&_addEvent(a,"blur",c)}},v=null;_getWindow=function(a){return null!=a&&a==a.window?a:9===a.nodeType?a.defaultView||a.parentWindow:!1};_camelCase=function(a){return a.replace(z.rmsPrefix(),"ms-").replace(z.rdashAlpha(),
_fcamelCase)};_fcamelCase=function(a,c){return(c+"").toUpperCase()};_trim=function(a){return a.replace(/^ +/,"").replace(/ +$/,"")};_getCss=window.getComputedStyle?function(a,c){return window.getComputedStyle(a,null)[_camelCase(c)]||!1}:function(a,c){var d,e,g=a.currentStyle&&a.currentStyle[c],h=a.style;null==g&&h&&h[c]&&(g=h[c]);if(z.rnumnonpx().test(g)&&!z.rposition().test(c)){d=h.left;if(e=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;h.left="fontSize"===c?"1em":g;
g=h.pixelLeft+"px";h.left=d;e&&(a.runtimeStyle.left=e)}return""===g?"auto":g};_getSize=function(a,c){var d="width"==c?"Width":"Height";if(a!==window&&a!==document){d=a["offset"+d];if(isNaN(d)||!d)d=_getCss(a,c);isNaN(d);return parseInt(d)}try{if(a===window)return window["inner"+d]||document.documentElement["client"+d]||document.body["client"+d];if(a===document)return document.body["client"+d]}catch(e){return rspkr.log("[RSLib._getSize] Error: "+e.message,3),0}};_scrollXY=function(a,c,d,e){var g=/X/.test(c),
h=_getWindow(d);if(void 0===e)return h?c in h?h[c]:h.document.documentElement[a]||document&&document.body&&document.body[a]:d[a];h?h.scrollTo(g?$rs.scrollLeft(h):e,g?e:$rs.scrollTop(h)):d[a]=e};_addEvent=document.addEventListener?function(a,c,d){a.addEventListener&&a.addEventListener(c,d,!1)}:function(a,c,d){a.attachEvent&&a.attachEvent("on"+c,function(c){d(c,a)})};_removeEvent=document.removeEventListener?function(a,c,d){a.removeEventListener&&a.removeEventListener(c,d,!1)}:function(a,c,d){a.detachEvent&&
a.detachEvent("on"+c,d)};return{meta:{revision:"3715"},init:function(){window.ReadSpeaker.Sizzle?(v=ReadSpeaker.lib.Facade.eq,ReadSpeaker.lib.Facade.adapterInit(I),ReadSpeaker.log("[rspkr.l.RSLib] Initialized."),rspkr.Common.dispatchEvent("onAdapterReady")):ReadSpeaker.log("[rspkr.l.RSLib] Error, Sizzle unavailable.",3)}}}();
