/*
 2012 ReadSpeaker International B.v.

 @class ReadSpeaker.ui
 @namespace ReadSpeaker.ui
 @memberOf ReadSpeaker
*/
ReadSpeaker.ui=function(){var a=null,f=[],t=[],y=!1,v=function(h){h=h||window.event;h.returnValue=!1;if(h=h.originalEvent)h.cancelBubble=!0,h.returnValue=!1;h&&h.preventDefault&&h.preventDefault();h&&h.stopPropagation&&h.stopPropagation()},l=function(){rspkr.log("[rspkr.ui] Attempting to add click events.");var h=$rs.get("."+rspkr.ui.rsbtnClass+" .rsbtn_play"),a=null;$rs.isArray(h)||(h=[h]);for(var c=0,r=h.length;c<r;c++)if($rs.unregEvent(h[c],"click",ReadSpeakerDefer.clickhandler),a=h[c]?$rs.getAttr(h[c],
"data-rsevent-id"):"_bogus_",rspkr.l.f.eq.store[a]&&rspkr.l.f.eq.store[a].click)rspkr.log("[rspkr.ui] Click event already existed on "+h[c],2);else{$rs.regEvent(h[c],"click",function(c){v(c);window.readpage(this)});rspkr.ui.addFocusHandler(h[c],!0,h[c].parentNode);rspkr.log("[rspkr.ui] Added click event to: "+h[c],1);try{$rs.getAttr(h[c],"role")||$rs.setAttr(h[c],"role","button")}catch(b){rspkr.log("[rspkr.ui] Could not add role attribute.",2)}}},A=function(h){for(var a=$rs.get("a"),c=0,r=a.length;c<
r;c++)if(a[c].href&&a[c].href==h)return a[c];return!1},x=function(h){for(var a in f)if(f[a]&&f[a].getContainer&&f[a].getContainer()==h)return f[a];h=new rspkr.ui.Player(h);f.push(h);return h},z=function(){rspkr.log("[rspkr.ui] Initiating global callbacks");rspkr.ui.rsbtnClass=rspkr.cfg.item("ui.rsbtnClass")||"rsbtn";window.readpage=function(a,c){if(rspkr.ui.initrun){if(/ios|ipad|iphone|ipod|android/i.test(window.navigator.userAgent)){var h=window.rspkr;h.audio=new Audio;h.audio.play();h.audio.pause()}rspkr.ui.showPlayer(a,
c)}};window.rshlexit=function(h){rspkr.HL.chunking&&rspkr.HL.chunking.destroy();void 0!==h&&"false"!==h||a.stop();setTimeout(function(){rspkr.c.dispatchEvent("onAfterSyncExit",window)},1E3)};window.rshlinit=C().sync.init;window.rshlsetContent=C().sync.setContent;window.rshlsetId=C().sync.setId;window.rshlsync=function(h,c){for(var a=h.split(","),b=c.split(","),e=0,f=h.length;e<f;e++)C().sync.execute(a[e],b[e])};window.rshlcontinue=function(){function h(c){if(!rspkr.HL.chunking.entracte.src){c=encodeURIComponent(decodeURIComponent(rs.cfg.getPhrase(c)));
var a={},r;for(r in rspkr.c.data.params)rspkr.c.data.params.hasOwnProperty(r)&&(a[r]=rspkr.c.data.params[r]);r=rspkr.Common.data.selectedText;var b=rspkr.Common.data.selectedHTML;rspkr.Common.data.selectedText=c;rspkr.Common.data.selectedHTML="";a.text=c;a.output="audio";c=rspkr.c.buildReadSpeakerCall(a);rspkr.HL.chunking.entracte.src=c;rspkr.Common.data.selectedText=r;rspkr.Common.data.selectedHTML=b}rspkr.HL.chunking.entracte.volume=parseFloat((rspkr.st.get("hlvol")||100)/100);rspkr.HL.chunking.entracte.play()}
if(rspkr.HL.chunking){rspkr.log("[rspkr.ui.rshlcontinue]");rspkr.HL.chunking.chunkEnded=!0;var c=$rs.get("#sync"+rspkr.HL.html5.synclist[rspkr.HL.html5.synclist.length-1][2]),c=$rs.offset(c);if(rspkr.HL.chunking.continueHref){var a=rspkr.cfg.item("cb.chunking.pause",void 0,!0);if(-1==rspkr.HL.chunking.continueTime)if(rspkr.log("[rspkr.ui.rshlcontinue] Waiting for user interaction"),rs.ui.getActivePlayer().pause(),$rs.addClass(rspkr.ui.getActivePlayer().getContainer(),"rsautopaused"),h("chunkcontinue"),
a&&"function"==typeof a)rspkr.log("[rspkr.ui.rshlcontinue] Running custom callback",3),a();else{rspkr.log("[rspkr.ui.rshlcontinue] Showing default continue button");a=document.createElement("div");a.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");$rs.addClass(a,rspkr.ui.rsbtnClass+" rspopup rsresume");var b=$rs.findIn(a,"a");b.removeAttribute("href");$rs.regEvent(b,"click",function(c){rspkr.c.dispatchEvent("onChunkResume",window)});$rs.findIn(b,".rsbtn_text").innerHTML="<span>"+rs.cfg.getPhrase("chunkbutton")+
"</span>";document.body.appendChild(a);a.style.display="block";c.left+=15;b=c.left+$rs.width(a)-$rs.width(window);0<b&&(c.left-=b);a.style.left=c.left+"px";a.style.top=c.top+15+"px"}else 0==rspkr.HL.chunking.continueTime?(rspkr.log("[rspkr.ui.rshlcontinue] Autoplay"),rspkr.c.dispatchEvent("onChunkResume",window)):isNaN(rspkr.HL.chunking.continueTime)?rspkr.log("[rshlcontinue] Invalid time parameter!",3):(rspkr.log("[rspkr.ui.rshlcontinue] Autoplay with "+rspkr.HL.chunking.continueTime+" seconds delay"),
5<=rspkr.HL.chunking.continueTime&&h("chunkwait"),a&&"function"==typeof a&&a(rspkr.HL.chunking.continueTime),rspkr.HL.chunking.stall=!0,setTimeout(function(){rspkr.HL.chunking.stall=!1},1E3*rspkr.HL.chunking.continueTime),rspkr.HL.chunking.timer=setTimeout(function(){rspkr.c.dispatchEvent("onChunkResume",window)},1E3*rspkr.HL.chunking.continueTime))}else rspkr.log("[rshlcontinue] No continue href found!")}};var h=rspkr.c.data.browser;h&&(/iphone|ipad|ios|android/i.test(h.OS)||"android"==h.name.toLowerCase())?
($rs.regEvent(document.body,"touchstart",function(a){rspkr.ui.setPointerPos(a);return!0}),$rs.regEvent(document.body,"touchend",function(a){rspkr.ui.setPointerPos(a);rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(document,"selectionchange",function(a){rspkr.c.data.setSelectedText(a);return!0})):($rs.regEvent(document.body,"mousedown",function(a){rspkr.ui.setPointerPos(a);return!0}),$rs.regEvent(document.body,"mouseup",function(a){"opera"===h.name.toLowerCase()?setTimeout(function(){rspkr.c.data.setSelectedText(a)},
50):rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(window,"mouseup",function(a){"opera"===h.name.toLowerCase()?setTimeout(function(){rspkr.c.data.setSelectedText(a)},50):rspkr.c.data.setSelectedText(a);return!0}),$rs.regEvent(document.body,"keydown",rspkr.ui.setPointerPos),$rs.regEvent(document.body,"keyup",function(a){rspkr.c.data.setSelectedText(a);return!0}))},u=function(){document.removeEventListener?document.removeEventListener("click",window.ReadSpeakerDefer.clickhandler,!1):document.detachEvent&&
document.detachEvent("onclick",window.ReadSpeakerDefer.clickhandler);if(ReadSpeakerDefer.deferred){var a=ReadSpeakerDefer.deferred,b=null;if("a"!=a.tagName.toLowerCase()){for(b=a;"body"!=b.tagName.toLowerCase()&&(b=b.parentNode,"a"!=b.tagName.toLowerCase()););a=b}ReadSpeakerDefer.isRSLink(a)&&(rspkr.log("[rspkr.ui] Activating deferred element: "+a),$rs.removeClass(a.parentNode,"rsdeferred"),rspkr.ui.showPlayer(a));ReadSpeakerDefer.deferred=null}},g=function(h,b,c){rspkr.log("[rspkr.ui.showPlayer]");
c=c||!1;var r="string"==typeof h?A(h):h,e=r?$rs.closest(r,".rsexpanded"):void 0,e=$rs.hasClass(e,"pre-expanded")?void 0:e,f=rspkr.HL.chunking?rspkr.HL.chunking.currentChunkNumber:1;if(e&&!$rs.isArray(e)&&rspkr.ui.getActivePlayer()&&1==f&&rspkr.ui.getActivePlayer().getContainer()==e)rspkr.log("Player already active, calling Player.restart() instead"),rspkr.ui.getActivePlayer().restart();else{rspkr.HL.chunking&&rspkr.HL.chunking.destroy();rspkr.HL.chunking&&rspkr.HL.chunking.html5support&&(rspkr.HL.chunking.entracte=
new Audio,rspkr.HL.chunking.entracte.play(),rspkr.HL.chunking.entracte.pause());rspkr.c.dispatchEvent("onBeforeParamsSet",window,[r]);e="string"==typeof h?h:$rs.getAttr(r,"href");f=null;"string"==typeof h&&(f=e.match(/readid=[^&]+/gi),h=e.match(/readclass=[^&]+/gi),f&&0<f.length&&rspkr.HL.Restore.Storage.readId.push(f[0].replace("readid=","").split(",")),h&&0<h.length&&rspkr.HL.Restore.Storage.readClass.push(h[0].replace("readclass=","").split(",")));rspkr.c.data.selectedHTML="";rspkr.c.data.setParams(e);
void 0!==$rs.getAttr(r,"data-target")&&null!==$rs.getAttr(r,"data-target")&&(f=$rs.getAttr(r,"data-target"),f=$rs.get(f),"object"===typeof f&&(b=f));b&&!c?(f=$rs.get(b),$rs.addClass(f,rspkr.ui.rsbtnClass+" rsfloating"),rspkr.basicMode&&($rs.removeClass(f,"rshidden"),$rs.addClass(f,rspkr.ui.rsbtnClass+" rsvisible"))):f=$rs.closest(r,"div."+rspkr.ui.rsbtnClass);if(!0===rspkr.cfg.item("survey.allowed")){b=rspkr.c.cookie;c=rspkr.cfg.item("survey.cookieName")||"rspkrsurvey";r=rspkr.cfg.item("survey.cookieLifetime")||
15552E6;h=rspkr.c.data.params;if("1"===b.readKey(c,"nmbrdisplays")){rspkr.ui.Lightbox.show(rspkr.cfg.item("survey.url")+"?customerid="+h.customerid+"&lang="+h.lang,rspkr.st.r().replaceTokens(rspkr.cfg.item("ui.survey.buttons").join(),{rsSURVEY_BUTTON_CLOSErs:rspkr.cfg.getPhrase("close")}),!0,function(c){$rs.regEvent($rs.get("#rssurvey_button_close"),"click",rspkr.u.Lightbox.hide)},500);rspkr.log(b.updateKey(c,"nmbrdisplays","displayed",r),4);return}void 0===b.readKey(c,"nmbrdisplays")&&rspkr.log(b.updateKey(c,
"nmbrdisplays","1",r),4)}b=x(f);if(a&&a!=b||a&&e!==a.getHref())a.close(!0),rspkr.c.dispatchEvent("onUIClosePlayer",a.getContainer(),[0<rspkr.c.data.selectedText.length?"textsel":"nosel"]);c=(c=a)?c.getID():null;rspkr.c.dispatchEvent("onUIShowPlayer",window,[c,b.getID()]);b.setHref(e);a=b;b.show();return a}},e=function(h,b){b=b||a.getContainer();var c=$rs.findIn(b,".rsbtn_status");0===c.length&&(c=document.createElement("span"),c.className="rsbtn_status_overlay",c.innerHTML='<span class="rsbtn_status"></span>',
$rs.findIn(b,".rsbtn_exp").appendChild(c),c=$rs.findIn(b,".rsbtn_status"));$rs.css($rs.findIn(b,".rsbtn_status_overlay"),"display","block");if("nosound"===h)h='<a class="rsbtn_nosound">'+rspkr.cfg.getPhrase("nosound")+"</a>",c.innerHTML=h,(c=$rs.findIn(b,".rsbtn_nosound"))&&$rs.regEvent(c,"click",function(c){return a.nosound()});else if("loaderror"===h){var r=rspkr.c.data.getSaveData("link"),e=document.createElement("a");e.className="rsbtn_loaderror";e.innerHTML="[?]";e.href=r;$rs.regEvent(e,"click",
function(c){rspkr.ui.Lightbox.show("<iframe src='"+e.href+"' style='height:100%'></iframe>",null,!1,null,300);v(c)});c.innerHTML=rspkr.cfg.getPhrase("loaderror")||"An error has occurred, try again";c.appendChild(e)}else c.innerHTML=h},b=function(a,b,c){c=c||a;void 0===b&&(b=!0);$rs.focusIn&&"function"==typeof $rs.focusIn&&($rs.focusIn(a,function(){$rs.addClass(c,"rsfocus");!0===b&&(n=a);rspkr.Common.dispatchEvent("onFocusIn",window,[a,c])}),$rs.focusOut(a,function(){$rs.removeClass(c,"rsfocus");rspkr.Common.dispatchEvent("onFocusOut",
window,[a,c])}))},n=null,k=function(){n&&$rs.isVisible(n)&&(rspkr.log("[rspkr.ui.updateFocus] "+n.outerHTML),q(n))},q=function(a){$rs.focus&&"function"==typeof $rs.focus&&a&&$rs.focus(a)},p=function(a){if("iconon"==rspkr.st.get("hlicon")&&!y){var b=t.push(new w)-1;t[b].id=b;t[b].show(a);y=!0}},m=function(a){"iconon"==rspkr.st.get("hlicon")&&y&&(t.pop().hide(),y=!1)},w=function(){var a=0,b=0,c=null,r=52,e=null,f=null,k=null,n=function(a){a=a||c;$rs.addClass(a,rspkr.ui.rsbtnClass+" rspopup");rspkr.cfg.item("general.useCompactPopupButton")&&
$rs.addClass(a,"rscompact")},g=function(a){$rs.unregEvent(c,"mouseout",q);window.clearTimeout(e);var b,h=c.clientWidth+10,r;f=rspkr.ui.showPlayer(k,c,!0);r=f.getWidth();b=parseInt($rs.offset(c).left);(b=rspkr.ui.viewport.width+$rs.scrollLeft(document)-b)<r&&(b=parseInt($rs.css(c,"left"))-(r-(h-10)),$rs.css(c,"left",b+"px"));y=!1;$rs.unregEvent(k,"click",g);$rs.regEvent(k,"click",function(c){v(c);return f.restart()});v(a);return!1},q=function(c){e||(e=window.setTimeout(function(){m()},rspkr.cfg.item("general.popupCloseTime")||
2E3))},l=function(c){e&&(window.clearTimeout(e),e=null)},p=function(a,b){var h=document.body.getBoundingClientRect();$rs.css(c,{top:b-h.top+"px",left:a-h.left+"px",width:r+"px"})},m=function(){$rs.css(c,{display:"none",top:0,left:0});l();t.splice(null,1);y=!1;c.parentElement.removeChild(c)};(function(){var a=rspkr.c.findFirstRSButton();c=document.createElement("div");c.id=rspkr.getID();c.innerHTML=rspkr.cfg.item("ui.popupbutton").join("");n();k=$rs.findIn(c,".rsbtn_play");$rs.setAttr(k,"href",a?$rs.getAttr(a,
"href"):null);(a=rspkr.cfg.item("general.popupHref"))&&$rs.setAttr(k,"href",a);var a=$rs.getAttr(k,"href").match(/lang=([^&;]*)/i).pop(),b=$rs.findIn($rs.get(c),".rsbtn_play span.rsbtn_text span");b&&(b.textContent=b.innerText=rspkr.cfg.getPhrase("listen",a,"en_us"));$rs.setAttr(k,"title",rspkr.cfg.getPhrase("listentoselectedtext",a,"en_us"));$rs.regEvent(k,"click",g);document.body.appendChild(c)})();return{setPos:p,show:function(e){l(e);if(e&&"none"==$rs.css(c,"display")){var f=c.cloneNode(!0);f.id=
rspkr.getID();$rs.css(f,{display:"block",position:"absolute",top:0,left:0});document.body.appendChild(f);r=$rs.outerWidth(f)+3;document.body.removeChild(f);f=e.clientX||e.pageX||rspkr.ui.pointerX;e=e.clientY||e.pageY||rspkr.ui.pointerY;b=e>rspkr.ui.pointerY?e-$rs.scrollTop(document)+36>rspkr.ui.viewport.height-46?e-66:e+30:10>e-$rs.scrollTop(document)-66?e+30:e-51;a=10>f-$rs.scrollLeft(document)?f+10:f-$rs.scrollLeft(document)>rspkr.ui.viewport.width-(r+10)?rspkr.ui.viewport.width+$rs.scrollLeft(document)-
(r+10):f+0;p(a,b)}$rs.regEvent(c,"mouseout",q);$rs.regEvent(c,"mouseover",l);q(null);n();$rs.css(c,"display","block")},hide:m,id:null}},B={update:function(b,e,c){"hlspeed"===b&&e!==c&&(b=b.replace("hl",""),rspkr.c.converter[b]&&"function"==typeof rspkr.c.converter[b]&&(e=rspkr.c.converter[b](e)),rspkr.c.data[b]=e,a&&a.stop(),rspkr.pl.releaseAdapter())}},D=function(a,b,c,e,f,k){$rs.css(a,"background-color","rgb("+b+","+c+","+e+")");e<f?(e+=10,window.setTimeout(function(){D(a,b,c,e,f,k)},50)):k&&"function"===
typeof k&&k.apply(a,[])},C=function(){return rspkr.XP?rspkr.XP:rspkr.HL};_expand=function(a){"string"==typeof a&&(a=$rs.get(a));$rs.isArray(a)||(a=[a]);for(var b=0;b<a.length;b++)rspkr.ui.Player(a[b]).show(!0)};_animate=function(){var a=rs.cfg.item("ui.animate");if(a){var b,c=15,e=500;"object"==typeof a?(a.id&&(b=$rs.get(a.id)),a.count&&(c=a.count),a.interval&&(e=a.interval)):"string"===typeof a&&(b=$rs.get(a));if("boolean"===typeof a&&a||$rs.isArray(b)&&0==b.length||!b)b=$rs.get("."+rs.ui.rsbtnClass);
$rs.isArray(b)||(b=[b]);var f=c,k=setInterval(function(){0==f&&($rs.removeClass(b,"rsanimate"),clearInterval(k));1==f--%2?$rs.addClass(b,"rsanimate"):$rs.removeClass(b,"rsanimate")},e)}};return{meta:{revision:"3715"},initrun:!1,init:function(){var a=rspkr.Common.addEvent;a("onAfterModsLoaded",z);a("onReady",l);a("onReady",u);a("onReady",_animate);a("onSelectedText",p);a("onDeselectedText",m);a("onSettingsChanged",B.update);a("onAfterSyncInit",k);this.initrun=!0;rspkr.Common.dispatchEvent("onUIInitialized");
rspkr.log("[rspkr.ui] Initialized!")},addFocusHandler:function(a,e,c){b(a,e,c)},focus:function(a){q(a)},updateFocus:function(){k()},showOverlay:function(a,b){e(a,b)},settings:B,rsbtnClass:"",addClickEvents:function(){l()},initGlobalCallbacks:function(){z()},showPopupIcon:function(a){p(a)},processDeferred:function(){u()},showPlayer:function(a,b,c){return g(a,b,c)},expand:function(a){_expand(a)},pointerX:0,pointerY:0,setPointerPos:function(a){a.pageX&&(rspkr.ui.pointerX=a.pageX);a.pageY&&(rspkr.ui.pointerY=
a.pageY);a.originalEvent&&a.originalEvent.touches&&a.originalEvent.touches[0]&&a.originalEvent.touches[0].pageX&&(rspkr.ui.pointerX=a.originalEvent.touches[0].pageX);a.originalEvent&&a.originalEvent.touches&&a.originalEvent.touches[0]&&a.originalEvent.touches[0].pageY&&(rspkr.ui.pointerY=a.originalEvent.touches[0].pageY);return!0},viewport:{width:$rs.width(window),height:$rs.height(window)},popups:t,hl:function(a,b){window.setTimeout(function(){D(a,255,255,100,255,b)},200)},scroll:{INTERVAL:null,
STEPS:25,scrollToElm:function(a){$rs.isVisible(a)&&this.initScroll(a)},scrollToAnchor:function(a){for(var b=$rs.get("a"),c=null,e=0;e<b.length;e++){var f=b[e];if(f.name&&f.name==a){c=f;break}}this.initScroll(c)},initScroll:function(a){if(a){for(var b=a.offsetTop,c=a;c.offsetParent&&c.offsetParent!=document.body;)c=c.offsetParent,b+=c.offsetTop;b-=50;rs.cfg.item("ui.autoscrollOffset")&&!isNaN(rs.cfg.item("ui.autoscrollOffset"))&&(b-=rs.cfg.item("ui.autoscrollOffset"));clearInterval(rspkr.u.scroll.INTERVAL);
var c=rspkr.u.scroll.getCurrentYPos(),e=parseInt((b-c)/rspkr.u.scroll.STEPS);rspkr.u.scroll.INTERVAL=setInterval(function(){rspkr.u.scroll.scrollWindow(e,b,a)},10)}else document.location.hash=a},getCurrentYPos:function(){return document.body&&document.body.scrollTop?document.body.scrollTop:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:window.pageYOffset?window.pageYOffset:0},scrollWindow:function(a,b,c){var e=rspkr.u.scroll.getCurrentYPos(),f=e<b;
window.scrollTo(0,e+a);a=rspkr.u.scroll.getCurrentYPos();if(f!=a<b||e==a)window.scrollTo(0,b),clearInterval(rspkr.u.scroll.INTERVAL),"string"==typeof c&&(location.hash=c)}},activePlayer:a,getActivePlayer:function(){return a}}}();
ReadSpeaker.ui.Slider=function(){var a=this,f={handleClass:"",width:0,height:0,left:0,top:0,steps:-1,stepsize:-1,dir:"h",initval:-1,drop:null,start:null,dragging:null,click:null,labelDragHandle:"",labelStart:"",labelEnd:"",nudge:1},t={rsid:void 0,parent:void 0,ref:void 0},y=void 0,v=void 0,l=void 0,A=void 0,x=void 0,z=!1,u=0,g=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()};
this.initElement=function(a){if(!z){"string"==typeof a&&(a=document.getElementById(a));a.innerHTML+='<a href="javascript:void(0);" role="slider" class="keyLink" style="display:block; border:0;">&#160;</a>';var b=a.getElementsByTagName("a"),b=b[b.length-1],n=-1<f.steps?f.steps:100;b.relatedElement=a;$rs.setAttr(b,"title",f.labelDragHandle);$rs.setAttr(b,"aria-label",f.labelDragHandle);$rs.setAttr(b,"aria-orientation","h"==f.dir?"horizontal":"vertical");$rs.setAttr(b,"aria-valuemin",0);$rs.setAttr(b,
"aria-valuemax",n);$rs.setAttr(b,"aria-valuenow",f.initval||0);u=f.initval;$rs.regEvent(a,"mousedown",this.startDragMouse);$rs.regEvent(b,"click",function(a){g(a)});$rs.regEvent(b,"keyup",this.startDragKeys);$rs.regEvent(b,"dragstart",function(a){g(a)});$rs.regEvent(a,"touchstart",this.touchStart);$rs.regEvent(t.parent,"mousedown",this.mouseClick)}};this.mouseClick=function(e){if(!z&&!$rs.hasClass(t.ref,"dragged")){var b=a.findPos(e.target),n=e.clientX-(b.left-f.left);e=e.clientY-(b.top-f.top);l=
b.left;A=b.top;b=a.getCurrentVal({left:n,top:e});"function"==typeof f.click&&f.click(b,t);return!1}};this.findPos=function(a){var b=curTop=0;if(a.offsetParent){do b+=a.offsetLeft,curTop+=a.offsetTop;while(a=a.offsetParent);return{left:b,top:curTop}}};this.startDragMouse=function(e){rspkr.log("[rspkr.ui.Slider] startDragMouse");if(!z){a.startDrag(this);var b=e||window.event;y=b.clientX;v=b.clientY;$rs.regEvent(document.body,"mousemove",a.dragMouse);$rs.regEvent(document.body,"mouseup",a.releaseElement)}g(e);
return!1};this.startDragKeys=function(e){rspkr.log("[rspkr.ui.Slider] startDragKeys "+(e||window.event).keyCode);a.startDrag(this.relatedElement);$rs.regEvent(document.body,"keydown",a.dragKeys);$rs.regEvent(document.body,"keypress",a.switchKeyEvents);$rs.addClass(this.relatedElement,"rskeycontrolled");g(e)};this.touchStart=function(e){e=e.originalEvent;rspkr.log("[rspkr.ui.Slider] touchStart");z||(a.startDrag(e.target),y=e.touches[0].pageX,v=e.touches[0].pageY,$rs.regEvent(e.target,"touchmove",a.touchMove),
$rs.regEvent(e.target,"touchend",a.releaseElement));return!1};this.startDrag=function(e){rspkr.log("[rspkr.ui.Slider] startDrag");x&&a.releaseElement();l=e.offsetLeft;A=e.offsetTop;x=e;$rs.addClass(x,"dragged");"function"==typeof f.start&&f.start(t)};this.dragMouse=function(e){e=e||window.event;a.setPosition(e.clientX-y,e.clientY-v);a.valueChanged=!0;return!1};this.touchMove=function(e){e=e.originalEvent?e.originalEvent:e;g(e);a.setPosition(e.touches[0].pageX-y,e.touches[0].pageY-v);a.valueChanged=
!0;return!1};this.dragKeys=function(e){switch((e||window.event).keyCode){case 37:case 63234:a.valueChanged=!0;u-=f.nudge;break;case 38:case 63232:a.valueChanged=!0;u+=f.nudge;break;case 39:case 63235:a.valueChanged=!0;u+=f.nudge;break;case 40:case 63233:a.valueChanged=!0;u-=f.nudge;break;case 13:case 27:return a.releaseElement(),!1;case 9:return a.releaseElement(),!0;default:return rspkr.log("[rspkr.ui.Slider] return TRUE"),!0}!0===a.valueChanged&&(rspkr.c.dispatchEvent("onUISliderMove"),"function"==
typeof f.dragging&&f.dragging(a.getCurrentVal({skipValueCalculation:!0}),t));g(e);rspkr.log("[rspkr.ui.Slider] ready to return!");return!1};this.setPosition=function(e,b){var n,k=!1;n=e;var g=l,p=f.left,m=f.width,w="left";"v"==f.dir&&(n=b,g=A,p=f.top,m=f.height,w="top");n=g+n;-1<f.stepsize&&((n+p)%f.stepsize?n=f.stepsize*Math.ceil(n/f.stepsize)+p:k=!0);n>m+p?n=m+p:n<p&&(n=p);k||(x.style[w]=n+"px","function"==typeof f.dragging&&f.dragging(a.getCurrentVal(),t))};this.switchKeyEvents=function(){$rs.unregEvent(document.body,
"keydown",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.regEvent(document.body,"keypress",a.dragKeys)};this.releaseElement=function(){rspkr.log("[rspkr.ui.Slider] releaseElement");$rs.unregEvent(document.body,"mousemove",a.dragMouse);$rs.unregEvent(document.body,"mouseup",a.releaseElement);$rs.unregEvent(document.body,"keypress",a.dragKeys);$rs.unregEvent(document.body,"keypress",a.switchKeyEvents);$rs.unregEvent(document.body,"keydown",a.dragKeys);$rs.unregEvent(x,"touchmove",
a.touchMove);$rs.unregEvent(x,"touchend",a.releaseElement);$rs.removeClass(x,"dragged");$rs.removeClass(x,"rskeycontrolled");$rs.removeClass(x,"rsmousecontrolled");var e=a.getCurrentVal();x=null;"function"==typeof f.drop&&!0===a.valueChanged&&f.drop(e,t);a.valueChanged=!1;rs.ui.getActivePlayer()&&rs.ui.getActivePlayer().setProgress();return!1};this.getCurrentVal=function(a){var b,n=f.width;b="left";var k=f.left;"v"==f.dir&&(n=f.height,b="top",k=f.top);var g=-1<f.steps?f.steps:100,n=-1<f.stepsize?
f.stepsize:n/g;a=a?a[b]:$rs.css(t.ref,b).replace(/px/i,"");pos=Math.round(a)-k;b=Math.round(pos/n);"v"==f.dir&&(b=g-b);rspkr.log("[rspkr.ui.Slider] currentval: "+b);return a&&a.skipValueCalculation||isNaN(b)?u=Math.max(Math.min(u,g),0):u=b};return{init:function(e,b){"string"==typeof e&&(e=document.getElementById(e));if(e){var g=e.id||"data-readspeaker-slider-id-"+Math.floor(2E4*Math.random());e.setAttribute&&e.setAttribute("data-readspeaker-slider-id-","data-readspeaker-slider-parent-"+g);var k={width:function(){return $rs.width(e)},
height:function(){return $rs.height(e)}};if("object"==typeof b)for(var q in b)b.hasOwnProperty(q)&&void 0!==f[q]&&(f[q]=b[q]);q=!1;var l;"rsbtn_volume_slider"===e.className&&"jquery"===rspkr.l.f.currentLib()&&1.5>parseFloat(jQuery.fn.jquery)&&(l=e.parentNode.style.display,e.parentNode.style.display="block",q=!0);f.width=k.width();f.height=k.height();q&&(e.parentNode.style.display=l);-1<f.steps&&(f.stepsize=("h"==f.dir?f.width:f.height)/f.steps);k=document.createElement("span");k.setAttribute("data-readspeaker-slider-id-",
g);k.className=f.handleClass||"rsbtn_progress_handle rsimg";e.appendChild(k);t.rsid=g;t.parent=e;t.ref=k;g=$rs.css(k,"left");null!==g&&(f.left=parseInt(g.replace(/px/i,"")));g=$rs.css(k,"top");null!==g&&(f.top=parseInt(g.replace(/px/i,"")));-1<f.initval&&this.jumpTo(f.initval);f.labelStart&&(g=document.createElement("span"),g.className="slider-label-start",g.innerHTML=f.labelStart,e.appendChild(g));f.labelEnd&&(g=document.createElement("span"),g.className="slider-label-end",g.innerHTML=f.labelEnd,
e.appendChild(g));a.initElement(k)}},jumpTo:function(a){if(isNaN(a))return!1;var b=101,g=a;-1<f.steps&&(a=Math.round(a),b=f.steps+1);if(-1<a&&a<b){var k=f.width,l=f.left,p="left";"v"==f.dir&&(k=f.height,l=f.top,p="top",a=b-1-a);t.ref.style[p]=k/(b-1)*a+l+"px";$rs.setAttr($rs.findIn(t.ref,"a.keyLink"),"aria-valuenow",g)}},setCurrentValue:function(a){u=a},getInstance:function(){return t},getContainer:function(){return t.parent},releaseElement:function(){a.releaseElement()},startDragKeys:function(e,
b){a.startDragKeys.call(e,b)},disabled:function(){if(arguments)z=arguments[0];else return z}}};
ReadSpeaker.ui.Player=function(a){var f=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()},t=function(c){c=c||a;c=$rs.clone(c,!0,!0);var b;c.id=rspkr.getID();document.body.appendChild(c);$rs.css(c,{position:"absolute",top:"0",left:"0",display:"block",width:"auto"});$rs.css(c,"float","none");$rs.addClass(c,"rsexpanded");b=$rs.outerWidth(c)+3;c.style.display="none";
document.body.removeChild(c);return b},y=rspkr.getID(),v=this,l=[],A=0,x=!1,z=null,u=!1,g={_play:null,_pause:null,_stop:null,_vol:null,_settings:null,_dl:null,_closer:null,_powered:null,_get:function(c,b){var e;c="_"+c;e=a?this[c]&&0<this[c].length?this[c]:this[c]=$rs.findIn(a,b):null;return e==[]?null:e},play:function(){return this._get("play",".rsbtn_play")},pause:function(){return this._get("pause",".rsbtn_pause")},stop:function(){return this._get("stop",".rsbtn_stop")},vol:function(){return this._get("vol",
".rsbtn_volume")},settings:function(){return this._get("settings",".rsbtn_settings")},dl:function(){return this._get("dl",".rsbtn_dl")},pin:function(){return this._get("pin",".rsbtn_pin")},powered:function(){return this._get("powered",".rsbtn_powered")},closer:function(){return this._get("closer",".rsbtn_closer")},nosound:function(){return this._get("nosound",".rsbtn_nosound")},setPlayPause:function(a){rspkr.log("[rspkr.ui.Player.setPlayPause("+a+")]");a=a?$rs.getAttr(this.pause(),"data-rsphrase-play"):
$rs.getAttr(this.pause(),"data-rsphrase-pause");$rs.setAttr(this.pause(),"title",rspkr.c.decodeEntities(a));$rs.findIn(this.pause(),".rsbtn_btnlabel").innerHTML=a}},e=!1,b=[],n=function(){var c=null,c=rspkr.cfg,b=rspkr.cfg.getPhrases(rspkr.c.data.getParam("lang"));if(0==$rs.findIn(a,".rsbtn_exp").length){var e=$rs.hasClass(a,"rspopup")?c.item("ui.popupplayer"):c.item("ui.player"),c=document.createElement("div");c.className="rsbtn_exp rsimg rspart";c.innerHTML+=e.join("\n");a.appendChild(c)}c=g.pin();
e="Explorer"==rspkr.c.data.browser.name&&8>rspkr.c.data.browser.version;$rs.isArray(c)&&0==c.length&&(c=void 0);c&&!e&&rspkr.cfg.item("ui.usePin")?$rs.removeClass(c,"turnedOff"):c&&c.parentElement.removeChild(c);if(b){c=function(a,c){var b=$rs.findIn(a,".rsbtn_btnlabel");$rs.isArray(b)||(b=[b]);0<b.length&&(b[0].innerHTML=c)};g.pause()&&($rs.setAttr(g.pause(),"data-rsphrase-pause",b.pause),$rs.setAttr(g.pause(),"data-rsphrase-play",b.play),$rs.setAttr(g.pause(),"title",rspkr.c.decodeEntities(b.pause)),
c(g.pause(),rspkr.c.decodeEntities(b.pause)));g.stop()&&($rs.setAttr(g.stop(),"title",rspkr.c.decodeEntities(b.stop)),c(g.stop(),rspkr.c.decodeEntities(b.stop)));g.vol()&&($rs.setAttr(g.vol(),"title",rspkr.c.decodeEntities(b.volume)),c(g.vol(),rspkr.c.decodeEntities(b.volume)));g.settings()&&($rs.setAttr(g.settings(),"title",rspkr.c.decodeEntities(b.settings)),c(g.settings(),rspkr.c.decodeEntities(b.settings)));g.dl()&&($rs.setAttr(g.dl(),"title",rspkr.c.decodeEntities(b.download)),c(g.dl(),rspkr.c.decodeEntities(b.download)));
if(g.powered()){var e=$rs.findIn(g.powered(),".rsbtn_btnlabel"),f=b.speechenabled.match(/.*href="([^"]*)"/i).pop(),k=b.newwindow,h=document.createElement("p");h.innerHTML=b.speechenabled;k=(h.innerText||h.textContent)+(k?" ("+k+")":"");e&&(e.innerHTML=b.speechenabled);$rs.setAttr(g.powered(),"title",k);$rs.setAttr(g.powered(),"data-readspeaker-href",f);e=$rs.getAttr(g.powered(),"data-rsevent-id");(!e||rs.l.f.eq.store[e]&&!rs.l.f.eq.store[e].click)&&$rs.regEvent(g.powered(),"click",function(){window.open($rs.getAttr(this,
"data-readspeaker-href"))})}g.closer()&&($rs.setAttr(g.closer(),"title",rspkr.c.decodeEntities(b.closeplayer)),c(g.closer(),rspkr.c.decodeEntities(b.closeplayer)))}b=rspkr.c.data.browser;/safari/i.test(b.name)&&/iphone|ipad|ios/i.test(b.OS)||$rs.addClass(a,"rs-no-touch")},k={play:function(){rspkr.c.dispatchEvent("onUIBeforePlay");rspkr.log("[rspkr.ui.handlers.play]");b.progress&&b.progress.disabled(!1);k.setStateClass(a,"rsplaying");rspkr.basicMode&&k.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsplaying");
$rs.addClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");g.setPlayPause(!1);if(rspkr.ui.getActivePlayer()&&rspkr.ui.getActivePlayer().getContainer()==a)rspkr.pl.play(),u&&rspkr.pl.getProgress.apply(rspkr.pl,[!0,p,v]),rspkr.c.addEvent("onBeforeSyncInit",function(){u=!0;rspkr.pl.getProgress.apply(rspkr.pl,[!0,p,v])}),"flash"!==rspkr.pl.adapter||rspkr.displog.onVolumeAdjusted||rspkr.pl.setVolume(parseInt(rspkr.st.get("hlvol")||"100")),rspkr.c.dispatchEvent("onUIAfterPlay"),rspkr.cfg.execCallback("cb.ui.play",
a);else{rspkr.ui.getActivePlayer()&&rspkr.ui.getActivePlayer().close();var c=$rs.findIn(a,".rsbtn_play");window.readpage(c)}},pause:function(){rspkr.log("[rspkr.ui.handlers.pause]");k.setStateClass(a,"rspaused");rspkr.basicMode&&k.setStateClass($rs.findIn(a,".rsbtn_exp"),"rspaused");g.setPlayPause(!0);rspkr.pl.pause();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIPause");rspkr.cfg.execCallback("cb.ui.pause",a);rspkr.log("ReadSpeaker.ui.pause")},stop:function(){rspkr.log("[rspkr.ui.handlers.stop]");
b.progress&&b.progress.disabled(!0);k.setStateClass(a,"rsstopped");$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading");rspkr.basicMode&&k.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsstopped");g.setPlayPause(!0);$rs.setAttr(a,"data-readspeaker-current",0);b.progress&&(b.progress.jumpTo(0),q(0));rspkr.pl.stop();rspkr.pl.getProgress(!1);rspkr.c.dispatchEvent("onUIStop",a);rspkr.cfg.execCallback("cb.ui.stop",a);document.getElementById("rslightbox_contentcontainer")&&$rs.isVisible(document.getElementById("rslightbox_contentcontainer"))||
g.pause().focus();rspkr.HL.chunking&&1<rspkr.HL.chunking.currentChunkNumber&&(rspkr.HL.chunking.destroy(),rspkr.pl.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter());rspkr.log("ReadSpeaker.ui.stop")},setStateClass:function(a,b){a&&($rs.removeClass(a,"rspaused rsstopped rsplaying"),$rs.addClass(a,b))},vol:function(c){var e=$rs.findIn(a,".rsbtn_volume_container"),f=$rs.findIn(a,".rsbtn_volume");c=c.originalEvent;var g=function(a){var c=a.originalEvent,c=$rs.closest(c.srcElement||c.originalTarget,
".rsbtn_volume_container");if("click"===a.type){if(void 0===c||$rs.isArray(c)&&!c.length)$rs.css(e,"display","none"),$rs.unregEvent(document.body,"click",g),$rs.unregEvent(document.body,"keyup",g)}else"keyup"===a.type&&27===a.keyCode&&($rs.css(e,"display","none"),$rs.unregEvent(document.body,"click",g),$rs.unregEvent(document.body,"keyup",g))};$rs.css(e,"left",f.offsetLeft+"px");$rs.css(e,"display","none"==$rs.css(e,"display")?"block":"none");"block"===$rs.css(e,"display")?($rs.regEvent(document.body,
"click",g),$rs.regEvent(document.body,"keyup",g)):($rs.unregEvent(document.body,"click",g),$rs.unregEvent(document.body,"keyup",g));c&&c.stopPropagation&&c.stopPropagation();c.cancelBubble=!0;f={keyCode:13};c=$rs.findIn(e,".keyLink");try{b.vol.startDragKeys(c,f)}catch(k){rspkr.log("[rspkr.ui.handlers.vol] Error accessing object _sliders['vol']")}return!1},settings:function(){$rs.hasClass(a,"rsplaying")&&this.pause();rspkr.ui.Lightbox.show(rspkr.st.getHTML(),rspkr.st.getButtons(),!0,function(a){var b=
$rs.get("rslightbox_closer"),e=function(){document.removeEventListener?b.removeEventListener("click",e,!1):document.detachEvent&&document.detachEvent("onclick",e);rspkr.c.dispatchEvent("onSettingsClosed",window,[])};$rs.regEvent(b,"click",e);rspkr.ui.addClickEvents();rspkr.c.dispatchEvent("onSettingsLoaded",window,[]);rspkr.cfg.execCallback("cb.ui.settingsopened",a)})},close:function(c){k.pin(!0);c=c||!1;var e=rspkr.pl,f=!1;rspkr.HL.chunking&&rspkr.HL.chunking.destroy();c||rspkr.cfg.execCallback("cb.ui.beforeclose",
a);e.hasOwnProperty("getProgress")&&rspkr.pl.getProgress(!1);e.hasOwnProperty("releaseAdapter")&&rspkr.pl.releaseAdapter();$rs.setAttr(a,"data-readspeaker-current",0);b.progress&&b.progress.jumpTo(0);q(0);$rs.removeClass(a,"rsstopped rsplaying rspaused rsexpanded");if(rspkr.basicMode){var h;(h=$rs.findIn(a,".rsbtn_play"))&&$rs.removeClass(h,"rsexpanded")}$rs.hasClass(a,"rsfloating")&&($rs.removeClass(a,rspkr.ui.rsbtnClass),rspkr.basicMode&&($rs.removeClass(a,"rsvisible"),$rs.addClass(a,"rshidden")));
g.setPlayPause(!0);$rs.hasClass(a,"rspopup")&&(f=!0,$rs.removeClass(a,"rspopup"),$rs.css(a,"display","none"),a.parentNode.removeChild(a));$rs.css(a,"width","auto");delete rspkr.displog.onVolumeAdjusted;c||(rspkr.c.dispatchEvent("onUIClosePlayer",a,["userclick"]),rspkr.cfg.execCallback("cb.ui.close",a),rspkr.log("ReadSpeaker.ui.close: "+a));c||!1!==f||rspkr.ui.focus($rs.findIn($rs.get(a),".rsbtn_play"))},dl:function(c){$rs.hasClass(a,"rsplaying")&&this.pause();var b=(c=$rs.getAttr($rs.findIn(a,".rsbtn_play"),
"href"))?rspkr.c.data.getSaveData("dialog",c):rspkr.c.data.getSaveData("dialog"),e=!1;rspkr.log("[rspkr.ui.handlers.dl] Savelink: "+b);rspkr.u.Lightbox.show(this.getDlDialog(),this.getDlButtons(),!0,function(){var a=$rs.get("#rsdl_button_accept"),c=$rs.get("#rsdl_button_decline");a&&$rs.regEvent(a,"click",function(c){rspkr.u.Lightbox.hide(c);e="iOS"!==rspkr.c.data.browser.OS&&0<rspkr.c.data.selectedHTML.length?!0:"iOS"!==rspkr.c.data.browser.OS&&!0===rspkr.cfg.item("general.usePost")?!0:!1;if(!0===
e){c=null;if(document.getElementById("dliframe"))c=document.getElementById("dliframe");else{if(document.selection)try{c=document.createElement('<iframe name="dliframe">')}catch(f){c=document.createElement("iframe")}else c=document.createElement("iframe");c.name="dliframe";c.setAttribute("id","dliframe");c.setAttribute("style","display: none; position: absolute;");c.style.display="none";var g=document.getElementsByTagName("body"),k=null;0<g.length&&(k=g.item(0));if(k)k.appendChild(c);else return}c.src=
b;return!1}$rs.setAttr(a,"href",b);return!0});c&&($rs.regEvent(c,"click",function(a){f(a);rspkr.u.Lightbox.hide(a)}),setTimeout(function(){rspkr.ui.focus(c)},200));rspkr.c.dispatchEvent("onDownloadLoaded",window,[])})},pin:function(c,b){var e=a.id+"_pinnedHome",f=document.getElementById(e);b=b?!0:!1;if(!$rs.hasClass(g.pin(),"pinned")&&!c){if($rs.addClass(g.pin(),"pinned"),!f){var k=function(a,c){return window.getComputedStyle?window.getComputedStyle(a)[c]:a.currentStyle?a.currentStyle[c]:a.style[c]},
f=$rs.clone(a,!1,!0),h=a.offsetLeft,n=a.offsetTop;if(!b){f.style.width=k(a,"width").replace(/[^-\d\.]/g,"")-2+"px";f.style.height=k(a,"height").replace(/[^-\d\.]/g,"")-2+"px";for(var l="position left right top bottom margin-left margin-right margin-top margin-bottom".split(" "),q=0,m;m=l[q];q++){var p=$rs.css(a,m);$rs.setAttr(a,"data-css-"+m,p);p=k(a,m);"auto"!=p&&(f.style[m]=p)}f.className="rsbtn_pinnedHome rsbtn";for(f.id=e;f.hasChildNodes();)f.removeChild(f.lastChild);a.parentElement.insertBefore(f,
a)}a.style.position="fixed";a.style.top=n-$rs.scrollTop(document)+"px";a.style.left=h-$rs.scrollLeft(document)+"px"}}else if($rs.hasClass(g.pin(),"pinned")||c)if($rs.removeClass(g.pin(),"pinned"),f)for(f.parentNode.removeChild(f),l="position left right top bottom margin-left margin-right margin-top margin-bottom".split(" "),q=0;m=l[q];q++)p=$rs.getAttr(a,"data-css-"+m),$rs.css(a,m,p)},getDlDialog:function(){var a=rspkr.cfg.item("ui.dldialog").join("\n"),b={};b.rsTERMS_OF_USE_HEADINGrs=rspkr.cfg.getPhrase("touheading");
b.rsTERMS_OF_USE_BODYrs=rspkr.cfg.getPhrase("toubody");return rspkr.st.r().replaceTokens(a,b)},getDlButtons:function(){var a=rspkr.cfg.item("ui.dlbuttons").join("\n"),b={};b.rsTERMS_OF_USE_ACCEPTrs=rspkr.cfg.getPhrase("touaccept");b.rsTERMS_OF_USE_DECLINErs=rspkr.cfg.getPhrase("toudecline");return rspkr.st.r().replaceTokens(a,b)},nosound:function(){var a=rspkr.c.data.getSaveData("link");$rs.setAttr(g.nosound(),"href",a);return!0}},q=function(c){c=100<c?100:c;var b=$rs.findIn(a,".rsbtn_progress_played");
"object"===typeof b&&$rs.css(b,"width",c+"%");rspkr.cfg.execCallback("cb.ui.progresschanged",a,[c])},p=function(c){if(c.length){var f=parseInt(c[0]);c=parseInt(c[1]);var g=0==c?0:Math.round(f/c*100),k=$rs.findIn(a,".rsbtn_current_time"),h=$rs.findIn(a,".rsbtn_total_time"),n,l;b.progress&&(b.progress.setCurrentValue(g),e||(b.progress.jumpTo(g),q(g),k&&(k.innerHTML=n=m(f)),h&&(h.innerHTML=l=m(c)),rspkr.cfg.execCallback("cb.ui.timeupdated",a,[n,l])));rspkr.log("[rspkr.player.updateProgress] current time: "+
f+" total time: "+c);$rs.setAttr(a,"data-readspeaker-current",f);$rs.setAttr(a,"data-readspeaker-buffered",c);0<f&&$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading")}},m=function(a){a/=1E3;var b=parseInt(a%60),e=parseInt(a/60%60);a=parseInt(a/60/60%60);return(10>a?"0"+a:a.toString())+":"+(10>e?"0"+e:e.toString())+":"+(10>b?"0"+b:b.toString())},w=function(){e=!0},B=function(b,f){rspkr.log("_dropProgress ("+b+")",5);if(b){var g=b/100*$rs.getAttr(a,"data-readspeaker-buffered")/1E3;
rspkr.pl.setProgress(g)}e=!1},D=function(a){B(a)},C=function(c,e){rspkr.log("_dropVolume, "+c,5);c=0>c?0:20*c;b.vol&&b.vol.jumpTo(c/20);rspkr.pl.setVolume(c);rspkr.st.set("hlvol",c);rspkr.cfg.execCallback("cb.ui.volumechanged",a,[c]);return!1},h=function(c,e){if("keyLink"===c.className){var f="";$rs.hasClass(e,"rsbtn_volume_handle")?f="vol":$rs.hasClass(e,"rsbtn_progress_handle")&&(f="progress");var g={keyCode:13};b[f].startDragKeys(c,g)}else $rs.hasClass(e,"rsbtn_volume")&&(g={keyCode:13},f=$rs.findIn(a,
".rsbtn_volume_container"),f=$rs.findIn(f,".keyLink"),b.vol.startDragKeys(f,g))},E=function(a,f){if("keyLink"===a.className){var g="";$rs.hasClass(f,"rsbtn_volume_handle")?g="vol":$rs.hasClass(f,"rsbtn_progress_handle")&&(g="progress");b[g].releaseElement();e=!1}};return{init:function(){l.push([this.show,[]])},initVolume:function(){if(!$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))){var c=rspkr.cfg,e=rspkr.st.get("hlvol")||"100",e=parseInt(e)/100*5;b.vol=new rspkr.ui.Slider;b.vol.init($rs.findIn(a,
".rsbtn_volume_slider"),{handleClass:c.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:c.item("ui.volumeDir")||"v",steps:5,nudge:1,initval:e,dragging:C,click:C,labelDragHandle:c.getPhrase("slidervolumedesc")});c=$rs.findIn($rs.get(a),".rsbtn_volume_handle a");ui.addFocusHandler(c,!1,c.parentNode)}},show:function(c){c=c?!0:!1;var e=$rs.hasClass(a,"rsexpanded");$rs.rsid(a);a.id=y=a.id||rspkr.getID();ui=rspkr.ui;$rs.hasClass(a,rspkr.ui.rsbtnClass)||$rs.addClass(a,rspkr.ui.rsbtnClass);n();
var l=$rs.findIn(a,".rsbtn_status_overlay");$rs.isArray(l)||$rs.css(l,"display","none");"fallback"===rspkr.pl.adapter&&(rspkr.ui.showOverlay("nosound",a),$rs.addClass(a,"rsstopped"));$rs.addClass(a,"rsexpanded");if(rspkr.basicMode){var m;(m=$rs.findIn(a,".rsbtn_play"))&&$rs.addClass(m,"rsexpanded")}x||e||(g.stop()&&($rs.regEvent(g.stop(),"click",function(a){f(a);k.stop()}),ui.addFocusHandler(g.stop())),g.pause()&&($rs.regEvent(g.pause(),"click",function(b){f(b);$rs.hasClass(a,"rsplaying")?k.pause():
($rs.hasClass(a,"rsstopped")||$rs.hasClass(a,"rspaused"))&&k.play()}),ui.addFocusHandler(g.pause())),g.closer()&&($rs.regEvent(g.closer(),"click",function(a){f(a);k.close()}),ui.addFocusHandler(g.closer())),g.vol()&&($rs.regEvent(g.vol(),"click",function(a){f(a);k.vol(a)}),ui.addFocusHandler(g.vol())),g.dl()&&($rs.regEvent(g.dl(),"click",function(a){f(a);return k.dl(a)}),ui.addFocusHandler(g.dl())),g.settings()&&($rs.regEvent(g.settings(),"click",function(a){f(a);k.settings()}),ui.addFocusHandler(g.settings())),
g.pin()&&($rs.regEvent(g.pin(),"click",function(a){f(a);k.pin()}),ui.addFocusHandler(g.pin())),m=rspkr.cfg,$rs.setAttr(a,"data-readspeaker-current",0),$rs.setAttr(a,"data-readspeaker-buffered",0),$rs.isArray($rs.findIn($rs.get(a),".rsbtn_progress_container"))||(b.progress=new rspkr.ui.Slider,b.progress.init($rs.findIn($rs.get(a),".rsbtn_progress_container"),{handleClass:m.item("ui.progressHandleClass")||"rsbtn_progress_handle rsimg",dir:m.item("ui.progressDir")||"h",nudge:5,start:w,dragging:B,click:D,
labelDragHandle:m.getPhrase("sliderseek")}),e=$rs.findIn($rs.get(a),".rsbtn_progress_handle a"),ui.addFocusHandler(e,!1,e.parentNode)),$rs.isArray($rs.findIn($rs.get(a),".rsbtn_volume_slider"))||(e=rspkr.st.get("hlvol")||"100",e=parseInt(e)/100*5,b.vol=new rspkr.ui.Slider,b.vol.init($rs.findIn(a,".rsbtn_volume_slider"),{handleClass:m.item("ui.volumeHandleClass")||"rsbtn_volume_handle rsimg",dir:m.item("ui.volumeDir")||"v",steps:5,nudge:1,initval:e,dragging:C,click:C,labelDragHandle:m.getPhrase("slidervolumedesc")}),
e=$rs.findIn($rs.get(a),".rsbtn_volume_handle a"),ui.addFocusHandler(e,!1,e.parentNode)),rspkr.Common.addEvent("onFocusIn",h),rspkr.Common.addEvent("onFocusOut",E),rspkr.cfg.execCallback("cb.ui.open",a),x=!0);$rs.findIn(a,".rsbtn_powered")&&(m=$rs.findIn(a,".rsbtn_powered .rsbtn_btnlabel a"))&&((/Chrome|Safari|Opera/gi.test(rs.c.data.browser.name)||/Explorer/gi.test(rs.c.data.browser.name)&&8<=rs.c.data.browser.version)&&$rs.regEvent(m,"click",function(a){f(a)}),m.innerHTML='<span class="rsbtn_label_read">Read</span><span class="rsbtn_label_speaker">Speaker</span><span class="rsbtn_label_icon rsimg"></span>');
"0"!=$rs.getAttr(a,"data-readspeaker-current")&&(rspkr.pl.releaseAdapter(),$rs.setAttr(a,"data-readspeaker-current",0));"fallback"===rspkr.pl.adapter||c?(b.progress&&b.progress.disabled(!0),k.setStateClass(a,"rsstopped"),$rs.removeClass($rs.findIn(a,".rsbtn_progress_container"),"rsloading"),rspkr.basicMode&&k.setStateClass($rs.findIn(a,".rsbtn_exp"),"rsstopped")):(k.play(),rspkr.ui.focus(g.pause()));A=t(a);isNaN(A)||$rs.css(a,"width",A+(/[Ee]xplorer/.test(ReadSpeaker.c.data.browser.name)?1:0)+"px");
!$rs.hasClass(a,"rspopup")||rspkr.cfg.item("ui.pinnedPopup")||rspkr.basicMode||k.pin(!1,!0)},close:function(a){k.close(a)},stop:function(){k.stop()},nosound:function(){return k.nosound()},pause:function(){k.pause()},play:function(){k.play()},dl:function(a){k.dl(a)},settings:function(){k.settings()},vol:function(a){k.vol(a)},pin:function(a,b){k.pin(a,b)},restart:function(){rspkr.log("[rspkr.ui.restart]");k.stop();window.setTimeout(function(){k.play()},500);return!1},updateProgress:function(a){p(a)},
setProgress:function(a){B(a)},getContainer:function(){return a},getID:function(){return y},getWidth:function(){return A},setHref:function(a){z=a},getHref:function(){return z}}};
ReadSpeaker.ui.Lightbox=function(){var a=null,f=null,t=null,y=null,v=null,l=null,A,x=[],z=function(a){a=a||window.event;a.returnValue=!1;if(a=a.originalEvent)a.cancelBubble=!0,a.returnValue=!1;a&&a.preventDefault&&a.preventDefault();a&&a.stopPropagation&&a.stopPropagation()},u=function(){var a=$rs.css(l,"display");$rs.css(l,"display","none");var e=$rs.height(window),f=$rs.height(document),q=parseInt($rs.css(document.documentElement,"width")),p=$rs.width(document),m=$rs.absOffset(document.body),t=
0,u=0;isNaN(q)&&(q=$rs.width(window));m.left&&(u=m.left);m.top&&(t=m.top);$rs.css(v,{width:(p>q?p:q)+"px",height:(f>e?f:e)+"px",top:"-"+Math.abs(t)+"px",left:"-"+Math.abs(u)+"px"});$rs.css(l,"display",a);g()},g=function(){var a=$rs.outerWidth(l),e=$rs.outerHeight(l),f=$rs.width(window),g=$rs.height(window),e=A+80+50<g?A+80:g-50;l.style.height=e+"px";$rs.get("#rslightbox_content").style.height=e-80+"px";e>g?(l.style.top=$rs.scrollTop(document)+"px",l.style.marginTop="10px"):(l.style.top=g/2+"px",l.style.marginTop=
-(e/2-$rs.scrollTop(document))+"px");a>f?(l.style.left=$rs.scrollLeft(document)+"px",l.style.marginLeft="0"):(l.style.left="50%",l.style.marginLeft=-(a/2-$rs.scrollLeft(document))+"px")},e=function(a){27===a.keyCode&&rspkr.ui.Lightbox.hide()};return{init:function(){var b=rspkr.pub.Config;a=b.item("ui.overlay.overlayStyles");f=b.item("ui.overlay.contentStyles");t=b.item("ui.overlay.contentTemplate");document.querySelectorAll||(d=document,s=d.createStyleSheet(),d.querySelectorAll=function(a,b,e,f,g){g=
d.all;b=[];a=a.replace(/\[for\b/gi,"[htmlFor").split(",");for(e=a.length;e--;){s.addRule(a[e],"k:v");for(f=g.length;f--;)g[f].currentStyle.k&&b.push(g[f]);s.removeRule(0)}return b});rspkr.log("[rspkr.ui.Lightbox] Heartbeat!")},show:function(b,g,k,q,p){for(var m=0,w=document.body.getElementsByTagName("*"),B;B=w[m];m++)-1!=B.tabIndex&&(x.push([B,B.tabIndex]),B.tabIndex=-1);if("Explorer"!=rs.c.data.browser.name||6!=rs.c.data.browser.version)for(B=document.querySelectorAll("body > *"),m=0;w=B[m];m++)if("rslightbox_overlay"!=
w.id&&"rslightbox_contentcontainer"!=w.id&&"script"!=w.tagName.toLowerCase()){var D=w.getAttribute("aria-hidden");D&&w.setAttribute("data-original-aria-hidden",D);w.setAttribute("aria-hidden","true")}b=b||"";k=k||!1;v?(v.style.display="",l.style.display=""):(v=document.createElement("div"),v.id="rslightbox_overlay",l=document.createElement("div"),l.id="rslightbox_contentcontainer",l.innerHTML=rspkr.st.r().replaceTokens(t.join("\n"),{rsLIGHTBOX_CLOSE_LABELrs:rspkr.cfg.getPhrase("close")}),$rs.setAttr(v,
"style",a.join(";")),$rs.setAttr(l,"style",f.join(";")),document.body.appendChild(v),document.body.appendChild(l),rspkr.evt("onSettingsLoaded",{func:rspkr.st.r().handlers.changed.addButtonEvents,context:rspkr.st.r().handlers.changed,params:[this]}));m=$rs.get("rslightbox_closer");rspkr.ui.addFocusHandler(m,!1);$rs.regEvent(m,"click",function(a){z(a);rspkr.ui.Lightbox.hide(a)});$rs.regEvent(v,"click",rspkr.ui.Lightbox.hide);$rs.regEvent(document.body,"keyup",e);(w=document.documentElement)&&document.all&&
(w.style.overflowX=w.style.overflowY="hidden");if(b!=y||k)k=rspkr.cfg.getPhrase("close"),$rs.setAttr(m,"title",k),$rs.findIn(m,".rsbtn_btnlabel").innerHTML=k,$rs.get("#rslightbox_content").innerHTML="",$rs.css("#rslightbox_content","height","auto"),/^http/i.test(b)?$rs.findIn("#rslightbox_content","iframe").length||(k=document.createElement("iframe"),k.src=b,k.className="rslightbox-iframe",void 0===p&&(p=2E3),$rs.get("#rslightbox_content").appendChild(k)):"<"==b.substr(0,1)&&($rs.get("#rslightbox_content").innerHTML=
b),$rs.get("#rslightbox_buttons").innerHTML=g,y=b,"ar_ar"==rs.c.data.params.lang&&(-1==l.className.indexOf("rtl")&&(l.className=(l.className+" rtl").replace(/^\s+|\s+$/g,"")),$rs.setAttr($rs.findIn(l,"legend"),"align","right"));A=void 0===p||isNaN(p)?rspkr.basicMode?$rs.get("#rslightbox_content").scrollHeight:$rs.get("#rslightbox_content").clientHeight:p;b=$rs.findIn("#rslightbox_content",".rsform-row");for(m=0;m<b.length;m++)for(g=$rs.findIn(b[m],"input, a, select"),$rs.isArray(g)||(g=[g]),w=0;w<
g.length;w++)rspkr.ui.addFocusHandler(g[w],!1,b[m]);var C=$rs.findIn("#rslightbox_buttons",".rssettings-button-close");rspkr.ui.addFocusHandler(C,!1);$rs.regEvent(C,"click",function(a){z(a)});(b=$rs.findIn("#rsform_wrapper",".rssettings-button-gotobottom"))&&!$rs.isArray(b)&&rspkr.ui.addFocusHandler(b,!1);(b=$rs.findIn("#rslightbox_buttons",".rssettings-button-gototop"))&&!$rs.isArray(b)&&rspkr.ui.addFocusHandler(b,!1);var h=$rs.findIn("#rslightbox_content","input");$rs.isArray(h)&&0<h.length?setTimeout(function(){rspkr.ui.focus(h[0]);
rspkr.Common.addEvent("onFocusIn",function(a,b){a.className&&$rs.hasClass(a,"rssettings-button-gototop")?rspkr.ui.focus(h[0]):a.className&&$rs.hasClass(a,"rssettings-button-gotobottom")&&rspkr.ui.focus(C)})},200):$rs.isArray(h)||setTimeout(function(){rspkr.ui.focus(h)},200);u();$rs.regEvent(window,"resize",u);"function"==typeof q&&q.apply(this,[l])},hide:function(a){for(;0<x.length;){var f=x.pop();f[0].tabIndex=f[1]}if("Explorer"!=rs.c.data.browser.name||6!=rs.c.data.browser.version){a=document.querySelectorAll("body > *");
for(var f=0,g;g=a[f];f++){var q=g.getAttribute("data-original-aria-hidden");q?(g.setAttribute("aria-hidden",q),g.removeAttribute("data-original-aria-hidden")):g.removeAttribute("aria-hidden")}}z(a);v.style.display="none";l.style.display="none";$rs.unregEvent(window,"resize",u);$rs.unregEvent($rs.get("#rslightbox_closer"),"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(v,"click",rspkr.ui.Lightbox.hide);$rs.unregEvent(document.body,"keyup",e);(a=document.documentElement)&&document.all&&(a.style.overflowX=
a.style.overflowY="auto");rspkr.ui.updateFocus();rspkr.c.dispatchEvent("onSettingsClosed",window,[])},reposition:g}}();
